### ISSUE TITLE
"Vishva" project using JSweet

### ISSUE THREAD

**Issue by ssatguru** [cincheo/jsweet#109]
FYI
I finally got a prototype of my BabylonJS, JQueryUI, Java , JSweet project called "Vishva" up and running.
See
[http://ssatguru.appspot.com/BabylonJS-Vishva/intro.html](http://ssatguru.appspot.com/BabylonJS-Vishva/intro.html)

Source code at
[https://github.com/ssatguru/Vishva](https://github.com/ssatguru/Vishva)

**Comment by renaudpawlak** [comment]
Thanks Satguru. Great work! And this is really nice and a cool demonstrator for JSweet :)

So your project could be used as some sort of game level editor, right? I am wondering:

- is there a way to create new 3D objects and upload them to the world?
- are sensors/actuators enough to add some behavior to some objects? (I did not dive too much into them because I felt that I would need some instructions...). My first guess is that it would be nice to be able to add some code in order to implement new behaviors to the objects.... Some global code to detect some conditions such as win/loose conditions would also be nice :D... but I am probably pushing it beyond its purpose...

Thanks!

**Comment by ssatguru** [comment]
Thanks Renaud,

Though the main purpose of this project is not to create games , it can be used to create simple games.
It is meant more for creating "experiences". I will be adding VR support in the future. Very easy in BabylonJs. That would allow users to explore Worlds using Google Cardboard, Oculus etc.

Yes , you can create new 3D objects and upload them into the world. Basically the process is -create a 3d object using editor like blender, export them as Babylon file, add them to a asset folder, update a js config file and your are good to go.

I am not keen on adding support for code. Instead I want to use sensors/actuators to provide extensibility. I am in the process of making sensors/actuators into a separate project.  Ii want to develop that as some kind of a plugin system People write sensors and actuators as small javascript snippets and, add them using <script ..> tags, They are automatically discovered by the system and are available for use. Its nice way to provide reusability.

**Comment by ssatguru** [comment]
I am not very keen on adding support for code. Instead I want to use sensors/actuators to provide extensibility. I am in the process of making sensors/actuators into a separate project.  I want to develop that as some kind of a plugin system People write sensors and actuators as small JavaScript snippets and, add them using <script ..> tags, They are then automatically discovered by the system and are available for use. Its nice and easy way to provide reusability.

**Comment by renaudpawlak** [comment]
Sounds good! Thanks for these precisions.

**Comment by lgrignon** [comment]
Nice project! I shared it on facebook, it might interest someone ;)

**Comment by ssatguru** [comment]
Thanks Louis
