### ISSUE TITLE
maven module option not working

### ISSUE THREAD

**Issue by ssatguru** [cincheo/jsweet#114]
if I use the following option for jsweet-maven-plugin,1.1.0-SNAPSHOT
```
<module>commonjs</module>
```
I get the following kind of errors
ERROR: cannot find namespace 'babylon' at C:\projects-babylonjs\Vishva-JAVA\src\main\java\org\ssatguru\babylonjs\Vishva.java(59)
ERROR: cannot find namespace 'jqueryui' at C:\projects-babylonjs\Vishva-JAVA\src\main\java\org\ssatguru\babylonjs\VishvaGUI.java(3)

**Comment by lgrignon** [comment]
Hello, you could report your bugs / remarks in maven project repository: https://github.com/lgrignon/jsweet-maven-plugin/issues

That being said, I think there was a recent regression in module management in the JSweet core project. I hope I will have time to look into it.

**Comment by ssatguru** [comment]
The above error is reported by the transpiler, so might be a transpiler issue,

**Comment by renaudpawlak** [comment]
I confirm that it is a transpiler issue... Actually, more probably a Babylon candy issue.
I was able to reproduce the issue and I added a test for it but still need to make it pass. I am planning to work on candies tomorrow so I will keep you updated.

**Comment by renaudpawlak** [comment]
Ok. This was tricky. It is not a regression, not a bug really. It seems to me that neither babylon nor jquery ui definition files are "module ready". In general, definition files declare an external module that export something so that it can be used in a module system. These two don't (or I missed it). Maybe they expect that the user adds a declaration to specify the module name...

Anyway, to have workaround for these cases, I have enhanced JSweet so that it is now possible to specify a module for a candy package, in order to make it module compatible. What you have to do is to override the ``package-info.java`` file of the candy's exported module and define the ``@Module`` annotation.

For your case, what you need to do is to create in your source files the following files:

``src/main/java/def/babylonjs/babylon/package-info.java`` with the content:

```java
@jsweet.lang.Module("jquery-ui")
@jsweet.lang.Name("JQueryUI")
package def.jqueryui.jqueryui;
```

and ``src/main/java/def/jqueryui/jqueryui/package-info.java`` with the content:

```java
@jsweet.lang.Module("babylonjs")
@jsweet.lang.Name("BABYLON")
package def.babylonjs.babylon;
```

And it should work (make sure that you use latest JSweet version).

**Comment by ssatguru** [comment]
Thanks.
Will check this out.

**Comment by renaudpawlak** [comment]
WARNING: this way of doing thing was horribly hacky and has been removed from the current snapshot. Instead, you can declare the modules in the comment of a special java file called "module_defs.java". 

https://github.com/cincheo/jsweet/blob/master/src/test/java/source/candies/module_defs.java
