### ISSUE TITLE
RequireJS

### ISSUE THREAD

**Issue by GarouDan** [cincheo/jsweet#129]
Can we use the famous javascript library requirejs? (http://requirejs.org/)

If yes, how can we do it? I didn't find any candie.
If not, how can we put it to work?

**Comment by renaudpawlak** [comment]
That's a quite complicated subject, but the simple answer is 'yes, but quite differently from JavaScript and with some limitations'. The reason it is quite different is because we wanted to hide the complexity of using modules for Java programmers. So we have looked for a way to "automate" the use of modules through regular Java imports. Let me explain more.

What you need to do to use RequireJS is to compile your code with the ``<module>amd</module>`` option (note that to use the ``commonjs`` module system, you set ``<module>commonjs</module>``). Then, if you look at the generated code, you will notice that it bundles each Java package as a module, which is required by others through ``require`` statements (note that it is better to clean your output first to get rid of older output files). Additionally, if your program uses the jQuery API, you will note that JSeet also generates a ``require`` statement when using it. The require statement is automatically generated when importing a jQuery element in your Java program because the jQuery API is annotated with ``@Module("jquery")`` (you will see these annotations by looking at the code of the jQuery candy). Note that some ``@Module`` annotation are placed on function or fields, and some are placed on Java packages in the ``package-info.java`` files. You can tune the way the modules are required by changing the ``@Module`` annotations or setting new ones on packages.

So, to make it short, to generate RequireJS compatible code, all you need to do is to select the ``amd`` ``module`` option. JSweet will take care of the rest for you, but of course, you will need to have RequireJS enabled in your web page. 

I suspect that this use case will be enough for basic usage of modules, but might not be sufficient for complex usages. Also, I am unsure if the ``@Module`` annotations will be visible enough and that easy to use for regular programmers. Maybe we need an additional way to specify modules and requires, but at the moment we lack scenarios and feedback. So, don't hesitate to comment here.

**Comment by GarouDan** [comment]
Thx @renaudpawlak. In fact this is interesting. I could put it to work using the amd module, as you suggested. Works on a very intersting way.

Before your comment I created my own solution as in the code below:

`
	import static jsweet.dom.Globals.console;
	import static jsweet.lang.Globals.eval;
	
	public class Bootstrap {
	
		public static void main(String[] args) {
			Window w = (Window) eval("window");	
			console.log(w);
			
			String[] array = new String[0];
			array[0] = "../vendor/gserializer/gserializer.js";
			
			w.require(array);
		}
		
		class Window {
	
			public void require(String[] args) {
			}
		}
	}
`

Using this way I achieved a mode not just use the require on its full power as now I can use any strange javascript code inside the java if necessary.

Unfortunally in Java we can use something like `window.require = [some code]` like we can in Python for example. The life would be a little easy and we could write a generic candie.

Something that I thought, maybe would be interesting to the future is to port the Java reflection API. I think using it we could create several powerfull and interesting things. For example:

`
    Method require = jsweet.dom.Globals.window.getClass().getDeclaringMethod('require');
`

**Comment by renaudpawlak** [comment]
Thanks @GarouDan for your detailed input.
About reflection, please note that JSweet already provides an API that works very well in the JSweet context and which is simpler and more concise. I am thinking of the ``$get``, ``$set``, ``$apply``, and ``$new`` methods of the ``jsweet.util.Globals`` helper class.

Using these methods will allow you to do many things similar to reflection (and even more because in JS you can also modify your objects/classes at runtime on contrary to Java).

Typically, if you want to invoke the ``window.require`` method in JSweet, all you need to do is:

```java
import static jsweet.dom.Globals.window
[...]
$apply($get(window, "require"), "myModuleName");
```

To understand what's happening here, you have to remember that JSweet is just a syntax mapper. So ``$get(target, expr)`` calls are translated to ``target[expr]``, and ``$apply(target, args)`` is simply translated to ``target(args)``.

So the given JSweet code *exactly* corresponds to the TypeScript code:

```JavaScript
window["require"]("myModuleName");
```

Remember: JSweet *is* JavaScript, with the Java typing and Syntax.

Note that you don't need to use the ``eval``method to access the ``window`` variable, but that's cool you have used it as a hack ;)

So, maybe one day, JSweet will support some Java reflection API in order to share some code between Java and JavaScript. Typically, ``target.getClass().getDeclaredField("f").get(target)`` could be syntactically translated to ``$get(target, "f")`` (i.e. ``target[f] in JS``). However, I am not sure that it would be worth the complexity. Using reflection should IMO be runtime specific and it is OK to use different API when running on a JRE and when running on a JS VM.

Now, back to the require issue, finally :)

The cool thing with JSweet is that it leverages TypeScript to map to JavaScript. TypeScript choice it is add a syntax layer to JavaScript in order to hide the differences between the various module systems out there. It means that the same program can be compiled targeting AMD (requirejs), or commonjs (Node.js). I thought that was a good approach, so I kept it in JSweet and made it even more transparent, so that you don't even need to explicitly require the modules (there are required automatically when you import an element that has been declared as being part of a module through the ``@Module`` annotation).

That said, I think that we need to make this system more flexible and allow the users to manually require a module. I see 2 possibilities here (we could to both).

- Solution 1: Have a @Require annotation that can annotate classes (and even packages) to ensure that the generated code requires the module... for example (this is a dummy example because you currenlty don't need this for jQuery since it is automatically required):
```java
import static def.jquery.Globals.$;
@Require("$", "jquery")
class MyClass {
   // some code using jQuery
}
```
- Solution 2: Have a ``jsweet.util.Globals.require`` helper method to allow the user to explicitly require a module in its code. That code would probably need to be executed globally at the beginning of a file in most cases.
```java
import static jsweet.util.Globals.require;
import static def.jquery.Globals.$;
class MyClass {
   static {
      require("$", "jquery");
   }
   // some code using jQuery
}
```

I prefer solution 1 because it is more declarative, but solution 2 would be more flexible and allow for conditional requires. 

That's it. Don't hesitate to tell me what you think.

**Comment by GarouDan** [comment]
@renaudpawlak 

Interesting, I have seen some more things about the @Module annotation and I saw it working on a jQuery example code. And I think keep this transparent in fact is a good effort.

About your proposal solutions, in my opinion I think implement the second solution first will be better because the Javascript and Java devolopers that have experience with modules will know exactly what they are doing. The annotation solution is a good one too, and make it available will be great! But as I said, in my point of view, make it available after the second one looks like a better way.

PS.: this $get, $set, $apply are awesome.

Thx.

**Comment by lgrignon** [comment]
Module management changed with JSweet 2+
