### ISSUE TITLE
Overloading problem

### ISSUE THREAD

**Issue by tomitrescak** [cincheo/jsweet#130]
When you overload with different number operators the result is inocrrect

```
package org.jsweet;

import static jsweet.dom.Globals.*;

/**
 * This is a very simple example that just shows an alert.
 */
class Tomi 
{ 
  public int a = 0;
  private String b;
  public int d = 3;

    Tomi(int m) { 
        a = 0;
    }
    Tomi(double d) {
        d = 2;
    }
}
```

Comes to:

```
"Generated from Java with JSweet 1.1.0 - http://www.jsweet.org";
namespace org.jsweet {
    /**
     * This is a very simple example that just shows an alert.
     */
    export class Tomi {
        public a : number = 0;

        private b : string;

        public d : number = 3;

        public constructor(m? : any) {
            if(((typeof m === 'number') || m === null)) {
                (() => {
                    this.a = 0;
                })();
            } else if(((typeof m === 'number') || m === null)) {
                var d : any = m;
                (() => {
                    d = 2;
                })();
            } else throw new Error('invalid overload');
        }
    }
}
```

There should be warning or error that such overload is not supported.

**Comment by renaudpawlak** [comment]
Fully agreed. A warning at least is required.

For explanation, this is a JSweet limitation because JSweet does not make any distinction between numbers (all int, long, byte, double, float, short are mapped to JavaScript number). It would be horrible to emulate Java numbers in JavaScript, so this is probably something that we will never do. In most cases (except for quite "low-level" programming), this limitation is not an issue IMO. Also, I think that it is a healthy trade-off in order to keep JSweet close to JavaScript and remain fully compatible with JavaScript frameworks.

Note that another thing you have to know about number in JSweet, is that when you pass a double to an int, JSweet round/truncates the double so that it behaves similarly to Java wrt the values.

**Comment by lgrignon** [comment]
Should be ok since JSweet 2+
