### ISSUE TITLE
ES7 async keyword

### ISSUE THREAD

**Issue by ghost** [cincheo/jsweet#138]
Hi,

Is there a annotation or another way to use ES7 async keyword?

Thanks

**Comment by renaudpawlak** [comment]
Right now, JSweet does not support the await/async construct. However, since TypeScript supports it since version 1.7, it would be quite easy to make it work (plus JSweet already supports ES6 promises).

If we refer to the example given [here](https://www.typescriptlang.org/docs/release-notes/typescript-1.7.html), I can draft a small proposal (note that I have not tried to compile it... it is just for having the main principles).

```java
import jsweet.lang.Async;
import static jsweet.util.Globals.await;
import static jsweet.dom.Globals.setTimeout;
import def.es6_promise.Promise;
[...]

@Async 
Promise<Void> printDelayed(String[] elements) {
    for (String element: elements) {
        await(delay(200));
        console.log(element);
    }
    return null;
}

@Async 
Promise<Void> delay(long milliseconds) {
    return new Promise<Void>(resolve -> {
        setTimeout(resolve, milliseconds);
    });
}

[...]
printDelayed(new String[] {"Hello", "beautiful", "asynchronous", "world"}).thenOnFulfilledFunction(() -> {
    console.log();
    console.log("Printed every element!");
});
```

A few notes about it:

- ``async`` is achieved with the ``@Async`` annotation
- ``async`` methods should always return a promise (even null but that can be confusing for Java programmers)
- ``jsweet.util.Globals`` would define the ``await`` helper function, which takes a promise and returns a promise (so you can write ``return await(...)`` in an ``@Async`` function)

Just curious to know what people think. Did I miss anything?

**Comment by lgrignon** [comment]
Hi, this is very exciting. async/await is a major feature when coming to asynchronism!

This is great but this solution missed a point. Let's take an example in TypeScript:
```typescript
async function askForBigAnswer() {
    return new Promise<number>(function(resolve, reject) {
        setTimeout(function() { resolve(42); }, 2000)
    });
}

async function getBigAnswer(): Promise<number> {
    var bigAnswer = await(askForBigAnswer());
    return bigAnswer;
}

getBigAnswer().then(function(answer) {
    console.log(answer);
});
```

In getBigAnswer, the type of bigAnswer is number, but when returned, bigAnswer is automatically wrapped into a Promise<number>.

We do not have such a thing in Java / JSweet, so I propose the following: 
```java
@Async 
Promise<Double> askForBigAnswer() {
    return new Promise<Double>((resolve, reject) -> {
        setTimeout(() -> { 
          resolve.accept(42); 
        }, 2000)
    });
}

@Async 
Promise<Double> getBigAnswer() {
  Double bigAnswer = await(getBigAnswer());
  return async(bigAnswer);
}

[...]
getBigAnswer().thenOnFulfilledFunction((Double bigAnswer) -> {
    console.log("the long-awaited answer: " + bigAnswer);
});
```
What do you guys think about it?

**Comment by renaudpawlak** [comment]
Looks like an good solution to me!
In this solution, the helper functions ``async``/``await`` can be seen as promise wrapper/unwrapper. In a way, I believe that the ``@Async`` annotation is not even needed anymore because it could be automatically deduced from the presence of an ``await`` invocation in the method body... maybe it could be kept for clarity, but I am not sure.

**Comment by renaudpawlak** [comment]
BTW, I believe that the promise API could be improved in JSweet. It could be a good occasion to do it.

**Comment by lgrignon** [comment]
I am going to work on this :) 2 years after :)

**Comment by lgrignon** [comment]
Very nice looking! :D

https://github.com/lgrignon/jsweet-model-dto-json-deserialization/blob/master/src/main/java/org/jsweet/examples/deserialization/ModelDeserializationExample.java#L39

**Comment by lgrignon** [comment]
Note: this is an ES6 specific feature. I wasn't able to add async / await methods to jsweet-core ES5 because we need Promises for this.
That's also why I didn't write unit tests. Maybe we should migrate unit tests to use es6 core candy.

**Comment by lgrignon** [comment]
TODO : document in language specs

**Comment by lgrignon** [comment]
Unit tests use ES6 ! :)
dc0d05f5

**Comment by lgrignon** [comment]
Updated documentation based on .tex: 
https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#asynchronous-programming

@renaudpawlak I added myself as co-author. Hope you won't mind.

**Comment by renaudpawlak** [comment]
As you know, you are most welcome as a co-author, as well as anyone who would want to contribute :) Glad to see you are moving forward!
