### ISSUE TITLE
New function export

### ISSUE THREAD

**Issue by WhiteTrashLord** [cincheo/jsweet#141]
I finally setup Jsweet successfully and could test it a bit.
In GWT I can export functions like this:

		JsUtils.export(window,"doSomething", new Function()
		{			
			
			 public void f()
			 {
				
			 }
			});

It would be great if something similar would be also possible in JSweet.
I want to invoke this functions in own Javascript code. I don't really like the current approach with classes.

**Comment by renaudpawlak** [comment]
There is of course a similar feature in JSweet. You can use the ``$set`` helper method of ``jsweet.util.Globals`` in order to write new properties (including functions) into any object. Here, if I understand well what ``JsUtil.export`` does, the equivalent in JSweet would be:

```java
import static jsweet.dom.Globals.window;
import static jsweet.util.Globals.function;

[...]

window.$set("doSomething", function(() -> {
	// impl
}));
```
 
Fairly easy as you can see.

Generally speaking, JSweet allows almost everything of what can be done in JavaScript. JSweet is JavaScript with Java syntax so it is usually straightforward to switch back and forth between JS and JSweet.

Check out the specs, and here is some more details about ``$get`` and other helper functions taken form a previous [discussion](https://github.com/cincheo/jsweet/issues/141).

> About reflection, please note that JSweet already provides an API that works very well in the JSweet context and which is simpler and more concise. I am thinking of the ``$get``, ``$set``, ``$apply``, and ``$new`` methods of the ``jsweet.util.Globals`` helper class.
> 
> Using these methods will allow you to do many things similar to reflection (and even more because in JS you can also modify your objects/classes at runtime on contrary to Java).
> 
> Typically, if you want to invoke the ``window.require`` method in JSweet, all you need to do is:
> 
> ```java
> import static jsweet.dom.Globals.window
> [...]
> $apply($get(window, "require"), "myModuleName");
> ```
> 
> To understand what's happening here, you have to remember that JSweet is just a syntax mapper. So ``$get(target, expr)`` calls are translated to ``target[expr]``, and ``$apply(target, args)`` is simply translated to ``target(args)``.
> 
> So the given JSweet code *exactly* corresponds to the TypeScript code:
> 
> ```JavaScript
> window["require"]("myModuleName");
> ```
> 
> Remember: JSweet *is* JavaScript, with the Java typing and Syntax.

**Comment by WhiteTrashLord** [comment]
Thank you. I will try it :)
