### ISSUE TITLE
Jsweet generated message

### ISSUE THREAD

**Issue by WhiteTrashLord** [cincheo/jsweet#142]
My Javascript code contains this first line:

"Generated from Java with JSweet 1.1.0 - http://www.jsweet.org";

Could this be changed to be a Javascript comment? It somehow feels wrong to me :)

**Comment by renaudpawlak** [comment]
Yah... My Java programmer part doesn't like it either :) But I was once told that it was common practice in JavaScript.

It's easy to change if people think that it is bad... Any votes?

**Comment by WhiteTrashLord** [comment]
All Javascript libraries I know use comments. For example:

/*! jQuery v3.0.0 | (c) jQuery Foundation | jquery.org/license */

https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js

**Comment by lgrignon** [comment]
Even if such strings are considered harmless in Javascript (i.e. "use strict"), it may be better to generate something totally neutral here.
I saw another transpiler which offers the ability to tune up the generated header:
@TranspilationComment("my super class was generated by JSweet")
class MyClass {
}
or maybe something more global, like a transpiler option (for maven users <transpilationComment>My super project was written in JSweet - this is not the original source</transpilationComment>

Unfortunately, I have no time to contribute for this now, maybe somebody could help?

**Comment by renaudpawlak** [comment]
I think that the point is not to add some way to configure the JSweet comment. I really don't want to spend time for such a minor feature that anybody can implement just by forking JSweet.

The point is to know if there are examples and reasons to use a plain string rather than a comment. So far I was not able to find any frameworks/transpilers using strings like we do. The only reason I can think of so far for using strings it to avoid them being removed when applying a minification engine (minification would remove comments). But really, I am not sure we want this feature and in any case it sound too hacky for me.

So, until someone gives better reasons, let's plan to transform the string into a comment.

**Comment by renaudpawlak** [comment]
Hey. I have just pushed this change. The message is now a comment.
Actually, I have also found an excellent reason to switch to a comment, which I explain below for the record.

With the new ``definitions`` option, JSweet is now able to generate its own definition files (``d.ts``) from the JSweet definitions (``def.*`` package). In ``d.ts`` files, statements and expressions are not allowed (only declarations). So the message raises TypeScript compilation mistakes... I think that's a good enough reason to switch to a comment :)
