### ISSUE TITLE
Using candies

### ISSUE THREAD

**Issue by WhiteTrashLord** [cincheo/jsweet#143]
I am still testing JSweet. I tried to use the candy History (History.js). But I have no idea how to use it. I can't use it the same way I would in real Javascript.
Maybe you can give me some help? :)

**Comment by renaudpawlak** [comment]
You need to declare the candy in your dependencies. First look it up in the [snapshots](http://www.jsweet.org/candies-snapshots/) (or in the releases if you want). You can also search it through our [Artifactory Maven repo](http://repository.jsweet.org/artifactory/).

Note that when you search and browse for candies on our website, you will access the Maven dep, but also the Javadoc API.

I have found it and the Maven dep is (for the latest version):

```xml
<dependency>
  <groupId>org.jsweet.candies</groupId>
  <artifactId>history</artifactId>
  <version>2.0.0-SNAPSHOT</version>
</dependency>
```

The Javadoc is there: http://public.jsweet.org/apidocs/snapshots/org/jsweet/candies/history/2.0.0-SNAPSHOT/

Once the dep is declared, you should be able to compile your project. Of course the generated code will need the referenced JavaScript libs to run.  If you are lucky (this is an in-progress feature), the JavaScript lib is included in the candy Jar and will be automatically extracted by JSweet in your project (so that you don't need to download it). Otherwise you shall download the lib manually (or you can use Bower or other similar tool).

I hope this will help.

**Comment by WhiteTrashLord** [comment]
Thanks for the fast answer. I have no problems to import candies. Now I use the latest history version and I have for example problems to use HistoryAdapter. Maybe you can give me some example code how to use this class with JSweet?

I want to test something like this:

  // Bind to StateChange Event
    History.Adapter.bind(window,'statechange',function(){ // Note: We are using statechange instead of popstate
        var State = History.getState(); // Note: We are using History.getState() instead of event.state
    });

**Comment by renaudpawlak** [comment]
I have never used History.js myself. You need to look at the API (and generated code) and try to figure out how to use it (double check first how similar libs are used in the examples). If you can't figure it out, then there might be a problem in the API and I will take a look.

**Comment by WhiteTrashLord** [comment]
I already checked the API. I would expect a lot of static methods to use it similar like in Javascript. But there aren't any :( Does it mean that many JSweet candies might be not usable because nobody tested them?

**Comment by renaudpawlak** [comment]
Maybe you don't see how to use it because sometimes the API slightly differs in JSweet and in JavaScript. I will take a closer look because I am surprised with what you are saying with static methods.

We have tested/used around 50 candies (we call then "trusted candies"; JQuery (and plugins), Underscore, Backbone, Angular, Ionic, Node.js, React.js, Threejs, Moment, .........). Some major candies such as Angular and IONIC are used in real applications that we develop for customers. 

Candies are generated automatically, which means that it is likely that candies similar to already-tested candies should work. For example, regarding the simplicity of History.js, I would be extremely surprised that it would not work (Angular for instance is FAR more complicated). Note that sometimes, there are issues just because the TypeScript defs are made for Node.js and not for the browser.

It would be indeed great to have a list of trusted candies (humain-validated candies) that everybody could update when they use it...  I will try to set up a first list when I have time.

**Comment by renaudpawlak** [comment]
Ok. I took some time to look at it. As I suspected, I believe that there is no JSweet-related issue here. The thing with history.js is that it is integrated directly in the TypeScript core lib, which makes it "special" and is handled as a special case in the TypeScript definition. That's probably why you got confused.

Since JSweet candies are translated from TypeScript definitions, I advise to lookup how these definitions are used when you meet an issue because most of the time, it is just a TypeScript issue. Of course, the JSweet community is far from being as big as the TypeScript one, but the point is that since JSweet is "just" a TypeScript to Java translation. So, you can rely on the TypeScript community to find answers to most of your problems (lookup the TypeScript version of your problem).

Here, if you refer to the definition file (which is provided in the JSweet candy in src/typings), you will see that it requires a special cast to access the Historyjs API. It is explained here for instance: http://stackoverflow.com/questions/18379009/history-js-and-typescript-historyjs-is-not-defined

(Note that since there is a History class defined in the core API, I am not even sure that it is that useful to use the History candy... but that's another story)

Anyway, I have created a gist to show how to use the history.js candy from JSweet: https://gist.github.com/renaudpawlak/0ad3995c97eb1e2313d611f81aad6507

I hope that it helps and that you understand that you can rely more on TypeScript community when you use JSweet -- I do it all the time ;)

**Comment by WhiteTrashLord** [comment]
Thank you very much for the example. I think this was a tricky one for a beginner :)

**Comment by renaudpawlak** [comment]
Indeed. If you can, tell me if it works for you so that we can add history.js to the list of "trusted candies" :D

**Comment by WhiteTrashLord** [comment]
I had finally some time to test it. It seems that your example doesn't work. I think it does work if the Javascript code is changed to this:   var Historyjs = window.History;

I thought using JQuery would be easy. But I also have a problem there :(

		$("a").click(new Function<JQueryEventObject, Object>() {
			
			@Override
			public Object apply(JQueryEventObject t)
			{	
		                t.preventDefault();		
				return null;
			}
		});

Probably this code is wrong. Can you tell me how to use it correctly?

**Comment by renaudpawlak** [comment]
For JQuery, or generally speaking with JSweet, when having a functional interface, you must use a Java 8 lambda expression (here ``e`` is a ``JQueryEventObject``):

```java
    $("a").click(e -> {
        e.preventDefault();     
        return null;
    });
```

Make sure that you fully understand (and use) Java 8 lambdas when using JSweet. Note that if the code you have written is correct in Java (I have never thought of writing such code because I thought that is would not be correct with Java 8), then maybe it should be supported by JSweet too... I will double check.

For Historyjs, I will do further testing and tell you ASAP.

**Comment by renaudpawlak** [comment]
BTW, if ``var Historyjs = window.History;`` works in JS, then you can use the following workaround in JSweet: ``Historyjs Historyjs = any(window.$get("History"));``. I'll check if I find a better way to write it but this should work.

**Comment by renaudpawlak** [comment]
I double checked and I think that it is the best way to use History.js with JSweet. I have updated my gist: https://gist.github.com/renaudpawlak/c9a11707ec590d47b33bcfbdf8b4b1a2. Does it work for you now?

**Comment by renaudpawlak** [comment]
I have opened a new issue for supporting the older object syntax in JSweet: #146

**Comment by WhiteTrashLord** [comment]
Thanks again for your help. It's really time for me to learn Java 8 :)

With your new code History.js seems to load successfully.
Sorry, I have one last problem.

Historyjs.pushState(null, $(this).text(), $(this).attr("href"));	
this code will become this JS code:

Historyjs.pushState(null, $(_this).text(), $(_this).attr("href"));

When I remove the '_' History.js finally works. What's the correct code this time? ;)

**Comment by renaudpawlak** [comment]
Surprising again. I can't believe how good you are at finding problems ;) Please continue reporting.
Can you give me the full code please so that I can understand to what object ``this`` is referring to?

**Comment by WhiteTrashLord** [comment]
Haha, I am only testing :)
Here you go:

		final Historyjs Historyjs = any(window.$get("History"));		
		
		Historyjs.Adapter.bind(window,"statechange",() -> { // Note: We are using statechange instead of popstate
			HistoryState state1 = Historyjs.getState(); // Note: We are using History.getState() instead of event.state			
			alert(state1.url);			
}); 		
		
		 $("a").click(e -> {
		        e.preventDefault();  		        
		        Historyjs.pushState(null, $(this).text(), $(this).attr("href"));		        
		        return null;
		    });

**Comment by renaudpawlak** [comment]
Ok, but if you use "this", it means that you are enclosing your click handler in a non-static method (which I don't see here). In Java, "this" always refers to the enclosing object, but in JavaScript it can be quite different (and as a Java programmer I prefer the Java way). So, when you write ``$(this)``, you are getting the jQuery object for your enclosing object, so I am not surprised it does not work. I believe you'd have the same effect in TypeScript.

Anyway, in JSweet, you have to understand "this" like in Java, not like in JavaScript.

I guess, that what you are trying to write would be in JSweet:

```java
		 $("a").click(e -> {
	            e.preventDefault();                 
	            Historyjs.pushState(null, $(e.target).text(), $(e.target).attr("href"));                
	            return null;
	        });		
```

Does it work?

**Comment by WhiteTrashLord** [comment]
Thanks, your code seems to work now. You can't create a variable like Globals.thispointer which results in a simple 'this' in the JS code?
Maybe you can change any as well.
What about this:

any("window.History")  it checks if the parameter is a String. If yes, it will simply print window.History in the JS code.

And with GWT I don't have this problems. I think most developer would use JSweet because they don't like Javascript. Do you plan to make the compiler more Javafriendly in future?

**Comment by renaudpawlak** [comment]
Yes, the GWT approach is very different because they implement the Java language... but then it is much harder to access JavaScript. 

JSweet is more like TypeScript but with the Java syntax. And yes, JSweet is supporting more and more Java, in order for Java programmers to be comfortable (note that the "this" problem you had is because "this" behaves like in Java, not like in JavaScript). For example, JSweet already supports function overloading, anonymous classes and static initialization (which are not available in TypeScript). I will make it more Java-complete along the way, but you can yourself contribute to the [J4TS](https://github.com/cincheo/j4ts) project to support more Java APIs.

Being able to mimic the JavaScript "this" with a ``jsweet.util.Global.thispointer`` field is a good idea. An issue should be created.

For being able to transform a string to a JS expression, you already have  ``eval("window.History")`` (from ``jsweet.lang.Globals.eval`` I think), which does a similar job. We could provide some sort of compile-time macro to do it... but I am afraid that people start to overuse it because they don't know how to write the same code in JSweet. It would be probably good for adoption, but bad for code quality...
