### ISSUE TITLE
add a $this helper field

### ISSUE THREAD

**Issue by renaudpawlak** [cincheo/jsweet#148]
Check if it is possible to have a `$this` macro to use the JavaScript 'this'...

**Comment by lgrignon** [comment]
Given that JSweet transpiles to TypeScript, it might be trickier than it sounds. TypeScript only reveals the JavaScript contextual this when using the old fashionned javascript function. TypeScript arrow functions (and now ES6 arrow functions) do not allow access to the contextual this.

The best is maybe to not rely on the Javascript which is, AFAIK, error prone and at the opposite of the Java spirit.

This is just my opinion, but since it would be pretty hard to develop, I am not sure it is worth it.

**Comment by renaudpawlak** [comment]
Some food for thoughts: https://github.com/Microsoft/TypeScript/wiki/'this'-in-TypeScript

**Comment by renaudpawlak** [comment]
I leaning towards a ``$macro`` helper to allow inserting any TS code when suitable. We need to be pragmatic...
