### ISSUE TITLE
Candies WebJars etc. and compilation target.

### ISSUE THREAD

**Issue by sekaijin** [cincheo/jsweet#150]
hi,
two subjects in my post:
I note that many projects face the same problem: the provision of a repository like maven for the librairies and Javascript framewoks

The Candies within this concern.
The project WebJars seeks to make available JavaScript libraries for use in the webapp
http://www.webjars.org/
in ClosureJavascriptFramework a project that intent to provide the tools to work with maven clojureScript the solution is a javascript jsar package as is for java jar, phar for php.
https://github.com/jlgrock/ClosureJavascriptFramework/wiki
then http://st-js.github.io/bridges.html

The target of the compilation.

currently the project target is typescript. then use the typescript tool chain to produce javascript.

I adhere to this idea and I do not question. I think it is good to keep typescript as intermediate language.

but with looking at the evolution of technology, I wonder if it is not opportune to consider complementary approach.

Implement a typescript compiler in Java directly without going through an interpreter as node.js, Rhino, or nashorn.
there are some as POC
https://github.com/vorburger/eclipse-typescript-xtext

But above all it may be worthwhile to add another target as wasm.

https://github.com/evanw/thinscript is an experiment to show that a language like typescript can be compiled to many targets.
the project has defined C, JS and WSAM. I have personally added (partially) Java.

I think a collaboration to a convergence with projects like webjars.org would propose the concept of candies to a wider community and in return a benefit many apackages defined by the community.

on compiling, the compiler thinscript even if it is an experiment proves daunting.
dispense with the interpreter in the toolchain simplifies chain, and realize more efficient and robust.

A+JYT

**Comment by renaudpawlak** [comment]
Hi there. Thank you for your input! Many things there. Difficult to deal with everything at once :)

- Webjars: we are already following the Webjar conventions. Check out the candies snapshots (e.g. jQuery), you will find that it contains the jQuery lib following the Webjars conventions (not all candies work, but some do). However, you are right, it is a very good idea to contact the Webjar project and see what can be done to factorize our efforts.
- ST-JS: their libs are manually written (on contrary to JSweet). I have approached them and they are quite open to collaboration. However, the JSweet and ST-JS are not fully compatible and since ST-JS is an older project with a lot of legacy, it seemed to much work to factorize our efforts at the time we spoke.
- ClosureJavascriptFramework: I don't know it too much so I will check when possible.

Regarding the target of compilation, our current idea it to use J2V8 to run the TypeScript compiler on the Java VM. This would clearly improve the overall transpiler performance. Implementing a TypeScript compiler directly in Java seems like a lot of work. In that case compiling directly to JavaScript seems like a more feasible idea...  ThinScript clearly looks interesting and I like the idea of having conditional directives depending on the target. It sounds quite experimental though. Generally speaking, there are a lot of other issues to be dealt with before adding other targets. I would even say that it looks out of scope for JSweet. But clearly, I'd be glad if someone worked in that direction ;)

**Comment by renaudpawlak** [comment]
For info: https://github.com/webjars/webjars/issues/1469
Hopefully there will be some outcome...
