### ISSUE TITLE
New intro paragraph for README

### ISSUE THREAD

**Issue by monperrus** [cincheo/jsweet#161]
Bug report: the intro paragraph in README does not show how great JSweet is.

Here is a tentative better intro paragraph for the README. I suggest to edit this issue directly to converge.
--Martin

JSweet allows you to write rich and responsive Web applications in Java through the use of JavaScript libraries and frameworks. With JSweet, Java programs are transpiled (source-to-source compiled) to Javascript for being run in browsers or in Node.js. 

* JSweet is safe and reliable. It provides web applications with type-checking and generates fully type-checked JavaScript programs. It stands on Oracle's Java Compiler (javac) and on Microsoft's TypeScript (tsc). 
* JSweet allows you to use your favorite JS library ([JSweet+Angular2](https://github.com/cincheo/jsweet-angular2-quickstart), [JSweet+threejs](https://github.com/cincheo/jsweet-examples-threejs), IONIC/Cordova, ...).
* JSweet enables you to share some code between server-side Java and client-side JavaScript. JSweet provides implementations for the core Java libraries for code sharing and legacy Java migration purpose.
* JSweet is fast, lightweight and interoperable. The generated code is regular JavaScript code, which implies no overhead compared to JavaScript, and can directly interoperate with existing JavaScript programs and libraries.

How it works? JSweet depends on typed descriptions of JavaScript APIs, defined in TypeScript, they are called "candies". You can even use part of the Java core API using the [J4TS](https://github.com/j4ts) candies. 

JSweet programs run on a JavaScript VM, not on a JVM, unless the programs only use Java APIs. So . With JSweet, you take advantage of all the Java tooling to program real JavaScript applications using the latest JavaScript libraries.

**Comment by lgrignon** [comment]
Good idea, the readme is a little bit "cold" 

It would be the opportunity to put the other examples link as well because developers often miss them:
- JSweet Node & Socket.IO example : https://github.com/lgrignon/jsweet-node-example
- JSweet JAX-RS server example : https://github.com/lgrignon/jsweet-jaxrs-server-example
which shares its model with 
- JSweet Cordova / Polymer example : https://github.com/lgrignon/jsweet-cordova-polymer-example
- JSweet Cordova / Ionic example : https://github.com/lgrignon/jsweet-cordova-ionic-example

Thanks anyway for improving!

**Comment by renaudpawlak** [comment]
That's complicated. First I am not sure that it is the role of the github site to show such "advertisement" statements. To me the github site is for developers and should focus on facts and pure technical details. We have jsweet.org for the "advertisement".

Comparison with GWT is complex because GWT 3 announces features that look very similar to JSweet (J2CL looks like a similar transpiler and Elemental's goal is to provide a Candy-like service). Despite I am myself convinced (and could certainly prove) that GWT 2 is far slower than JSweet (both at compilation and execution), I don't want to waste my time doing so and enter in such controversial debates, especially because JSweet and GWT do not share the same objectives and, in a way, it would be comparing apples and oranges. Enough has been said already on the topic (see for instance: http://www.jsweet.org/comparing-the-gwt-transpiler-and-jsweet/).

That said, without comparing with GWT, I believe that the intro could be improved and maybe focus more on JSweet core qualities and objectives (clearly, it is hard to write a good intro and there is always room for improvement). @lgrignon about the examples, I will certainly add them in the examples section.

@monperrus I will think about it. Meanwhile if you want to rework on your contribution  with my input, you are more than welcome. Thanks anyway!

**Comment by monperrus** [comment]
I'm not talking at all about advertisement. The goal of the intro is to understand **what JSweet is**. Currently, it's really hard (and many people directly go to Github).

I've removed the line about speed.

**Comment by renaudpawlak** [comment]
We can also remove the "Unlike GWT".
I believe that the line about speed can be reworded to emphasize the fact that JSweet is very light-weight and has low impedance to JavaScript, which is a good thing because you can use JSweet programs along with JavaScript ones (and vice-versa). In short: JSweet maximizes Java - JS interoperability in a direct and straightforward way.

**Comment by monperrus** [comment]
> We can also remove the "Unlike GWT".

Done 

> JSweet maximizes Java - JS interoperability in a direct and straightforward way.

This is not a fact :-) this sounds more like bullshit bingo ^^

**Comment by monperrus** [comment]
Note that you can also edit my initial post (click on the pen)

**Comment by renaudpawlak** [comment]
Yeah. I agree... it sounds like BS. But it is soooo important. In GWT, a Java object remains a Java object and you need to use JSNI or JSInterop to talk with JavaScript objects. In JSweet, a Java object *is* a JavaScript object. This makes a heck of a difference when using JavaScript frameworks or when you want your program to be used by JavaScript frameworks!!!

I will edit directly when I get better ideas on how to write it down as a fact ;)
