### ISSUE TITLE
Generated AMD modules fail at load-time due to dependency cycle

### ISSUE THREAD

**Issue by HeikkiAitakangas-Documill** [cincheo/jsweet#169]
Java-side imports from parent packages cause a failure in the transpiled code at require-load time. Requirejs' loader runs the code for the deepest package first, which means the parent package has not yet populated it's exports object.

This can be partially worked around using fully qualified class names instead of imports, but that gets fairly unreadable with the usual Java package hierarchy depths.

A project illustrating the problem is at https://github.com/HeikkiAitakangas-Documill/jsweet-amd-bug

**Comment by renaudpawlak** [comment]
Wow. Great bug report, thanks!! :D Will check asap. Is it working with commonjs modules?

**Comment by renaudpawlak** [comment]
Ok. After double checking, it appears that this bug was already encountered while working on Angular 2 (see my [blog post](http://www.jsweet.org/writing-angular-2-applications-with-java/)). After thinking more about the issue, it appeared that the way JSweet handled modules in version 1.1.x was not right for many reasons (the strategy was to created one ``module.ts`` file per package). Problems were:

- unintuitive generation (several files grouped in one file)
- unwanted additional modules added along the directory hierarchy
- some bugs (I think the way you have reported it shows it best, thanks) => this bug prevented dependency injection to work well in Angular 2.

So,  all these taken into account, I have decided to completely rework the way JSweet generates modules in version 1.2. It is much simpler now. One Java file = TS file = one module. Requires are still automatically generated, but on a per-file strategy then. So, if you use 1.2.0-SNAPSHOT, you should not have any problems (I will send a PR to your project so that you can see the changes).

IMO, this new strategy is globally much better (and simpler). It has some small drawbacks (for instance when using fully-qualified names) that should be improved in the future. Also, in future versions, we may consider grouping several files within a file using an annotation for instance...

**Comment by HeikkiAitakangas-Documill** [comment]
Thanks, that does fix the loading.
