### ISSUE TITLE
Static inner class reference bug

### ISSUE THREAD

**Issue by lgrignon** [cincheo/jsweet#173]
``` java
// Wrapping.java
package x;

public class Wrapping {
  public static class Inner {
  }
}

// Other.java
import x.Wrapping.Inner;
public class Other {
  public void pouet(Inner i) {
  }
}

```

raises a compilation error. Generated TS:

``` typescript
namespace ... {

    import Inner = x.Wrapping.Inner;

// ERROR: namesapce Wrapping not found
   public pouet(i : Wrapping.Inner) { 
        }
}
```

**Comment by renaudpawlak** [comment]
Same effect with inner enums:

```Java
public class C {
   public enum E {
      FIELD
   }
}

// somewhere in other file (E being imported)
if(f == E.FIELD) ...
```

E will not be found...

**Comment by negora** [comment]
I'm not sure, but I think that the issue that I'm going to mention might be related to this one. So I'm going to write about it here, instead of opening a new ticket.

I've just tried to use a `switch` statement with an `enum`, but the transpiler has failed. In Java, the `case` statements of a `switch` structure forces us to refer to the member of an `enum` by its "short" name, instead of the one that contains also the name of the `enum`. Example:

```java

public enum ContentType {
  JSON,
  XML;
}

switch (contentType) {
  case JSON:
    ...
  case XML:
    ...
  default:
    ...
}   
```
In order to make it compile, I've to replace the `switch` with a `if-else if-else`.

**Comment by renaudpawlak** [comment]
It does not look like the same bug to me. I was not able to reproduce a pb with ``switch`` and enums. Could you please show us the error and if possible the generated TypeScript code? Txs

**Comment by negora** [comment]
Ops! I don't know what I've done, but the `switch` is working now... I guess that I misinterpreted the log output. Sorry for the inconveniences.
