### ISSUE TITLE
Interop with TypeScript modules

### ISSUE THREAD

**Issue by bpilot** [cincheo/jsweet#180]
First, this project is a phenomenal effort that looks like it promises isomorphic Java -- making the JVM an alternative to Node for applications that actually do leverage common code between client and server. Top effort putting this together.

First, I am wondering if it is possible to keep some of the project as TypeScript modules.

Second, I am curious about typing:

Typescript seems to use structural typing to verify interfaces, while Java is nominally typed.

I.e., "implements ISomething" is required in Java while TypeScript is more Golang-like and just verifies the method signatures.

How is this difference handled by JSweet?

**Comment by renaudpawlak** [comment]
Thanks @bpilot. Yes, one of the goals of JSweet is to keep a JVM on the server and have a JS VM on the client... sharing the same code. About isomorphism, you may want to contact @GegeFr who is interested in that topic and who created a small framework based on JSweet in that direction.

Yes, it is totally possible to keep some of the project as TypeScript modules. They will interoperate very easily with JSweet modules. You will have to provide the definitions so that modules can compile. Two use cases:

- A JSweet module uses a TypeScript module: you need to write the Java definitions of your TypeScript module API (i.e. classes in ``def.moduleName`` package. These are bunch of classes holding native methods and empty constructors, so they are quite easy to write.
- A TypeScript module uses a JSweet module: you can just use the ``--declaration`` option of JSweet to generate the TypeScript ``d.ts`` files and use them in your tsc compilation path.

Regarding interfaces, that's a complicated topic, but basically, JSweet maps Java interfaces (and Java classes annotated with @Inerface) to TypeScript interfaces. From a typing perspective, it does not cause any real problems. At runtime however, Java programmers have to be aware that interfaces have no actual existence (they are erased just like TypeScript interfaces). So, JSweet adds some runtime properties to the objects in order to support ``instanceof`` on interfaces. This behavior could lead to TypeScript interoperability issues when sharing interfaces between Java and TypeScript. That's why ``instanceof`` and method overloading should be carefully used in JSweet when interoperating with TypeScript through interface sharing (and some minor adjustments may need to be made in the TypeScript code).

But I guess that the best way to have your own opinion is to try it ;)
