### ISSUE TITLE
Several cases where JSweet fails to compile code that is expected to work

### ISSUE THREAD

**Issue by hohwille** [cincheo/jsweet#182]
Hi there,
After my first hello world with JSweet, I wanted to challenge JSweet to figure out if it can be the basis of my vision. So far I failed fast and hard with JSweet compile errors. JSweet might still evolve and I am happy to assist so this is not a "giving up" already ;)
So to make things easy to reproduce, I created a github repo where I added a modified copy of your `jsweet-quickstart` that shows some compile problems I hit early on with JSweet:
https://github.com/hohwille/jsweet-test

It would be awesome if you could have a look.
As your FAQ (http://www.jsweet.org/faq/) does not list general limitations such as Java8 default methods or lambdas not supported by JSweet I would expect my code to compile and run.
Instead I get:
```
2016-11-04 20:57:42.042 INFO  JSweetTranspiler:1061 - net/sf/mmm/client/ui/api/widget/factory/UiSingleWidgetFactoryNativeButtonJSweet.ts(21,46): error TS2304: Cannot find name 'UiWidgetButton'.
ERROR: cannot find name 'UiWidgetButton' at net\sf\mmm\client\ui\api\widget\factory\UiSingleWidgetFactoryNativeButtonJSweet.ts(21)
2016-11-04 20:57:42.042 INFO  JSweetTranspiler:1061 - net/sf/mmm/client/ui/api/widget/factory/UiWidgetFactoryImplJSweet.ts(17,17): error TS2322: Type 'UiWidgetNative' is not assignable to type 'UiWidgetButton'.
ERROR: type 'UiWidgetNative' is not assignable to type 'UiWidgetButton' at C:\Projekte\mmm\workspaces\test\jsweet-test\src\main\java\net\sf\mmm\client\ui\api\widget\factory\UiWidgetFactoryImplJSweet.java(18)
2016-11-04 20:57:42.042 INFO  JSweetTranspiler:1061 -   Property 'setLabel' is missing in type 'UiWidgetNative'.
2016-11-04 20:57:42.042 INFO  JSweetTranspiler:1061 - quickstart/QuickStart.ts(38,26): error TS2339: Property 'iterator' does not exist on type 'JQuery'.
ERROR: property 'iterator' does not exist on type 'JQuery' at quickstart\QuickStart.ts(38)
2016-11-04 20:57:42.042 INFO  JSweetTranspiler:706 - transpilation process finished in 4102 ms
[ERROR] transpilation failed
org.apache.maven.plugin.MojoFailureException: transpilation failed with 3 error(s) and 1 warning(s)
```
Actually I consider my example as simple. I want to do a lot more magic stuff like this as you might imagine by looking at the code. But maybe there are some fundamental issues in JSweet and if those are fixed a lot more will be possible. I can not tell yet.
What I can tell so far is that I also made experiments with TypeScript and can easily create code that fits the spec but does not work as TypeScript is not really a professional language yet. To given an example: If you create a class X with a sub-class Y and X makes use of Y in a method the code will never work. That is one of a millions of reasons why I am frustrated about the entire web and would love to go for JSweet as a kind of GWT successor after GWT is about to die out and has some strong design flaws that disqualify it as future proof. JSweet seems to go in the perfect direction so I really believe in it and would also consider contributing after first getting experience with using JSweet.

**Comment by renaudpawlak** [comment]
I cloned and tried to compile your sample project. There are three errors. The last one about the ``iterator()`` on JQuery is not a real error because you are not supposed to use the ``iterator()`` method directly (it is said in the Javadoc). That leaves 2 errors, which are real errors.

The first one is a bug on default methods. Default methods are supported by JSweet to a certain extent (see this [test](https://github.com/cincheo/jsweet/blob/master/src/test/java/source/structural/DefaultMethods.java) for instance). I am pretty sure that I did not cover all the scenarios unfortunately. So thanks for reporting this bug. I will add your use case to the test and fix it ASAP.

The second one is about returning a ``Class<X>`` variable... I am not surprised there are issues here because that's a tricky case for JSweet. It was actually WIP but I did not run into any cases lately that would require more support.

At this point, I am unsure that you will be able to use JSweet to fulfill you dreamed world using Java for Web apps. It seems that you are really pushing it quite far in the sense that you are using a lot of Java idioms/constructs that are not used that often when you use pre-made JS frameworks and APIs. On the other hand, what I am quite sure of is:

1. Your contribution here is really valuable because you have digged out two bugs with a quite simple program (note that JSweet has a lot of [tests](https://github.com/cincheo/jsweet/tree/master/src/test/java/source) but boundaries cases are always complicated to deal with).
2. I believe that what you are trying to do belongs to JSweet's scope. I am myself currently building some sort of gaming framework with JSweet (for fun) and I wish I could use most constructs you are expecting here (even if I don't use them, it is good to know they are supported).
3. Last be not least, I think that the two bugs here are quite simple to fix (at least the first one is easy I think). I am not so sure about the second one but I have wanted to give it a try for a long time so that's a good occasion.

That's in the pipe!

**Comment by hohwille** [comment]
@renaudpawlak thanks for your support and your quick responses. I am really surprised by the strength that you put into the project. I have also created fully functional PRs for github projects that where neither merged nor even commented. 

On thing that I do not understand from the outside the the `Class<X>` problem. In the end in my case there is a method returning a Class object (the `<X>` will be lost anyway due to erasure) and the implementation is only returning a `.class` literal. So if such literal already works in the quickstart sample why should it not work if put into a method? Maybe the fix is also not hard to do... but I might also miss something under the hood...

Also thanks for your honest way but I think that for "my dream" there may be some issues to solve but not that much and I also do not expect magic (I do not want real reflection support, etc.) so most of the things are already there. One thing that might be an edge-case is type support for something like List<String> to figure out the component type what is actually String here. But I will also dig deeper into what JSweet Candies can do. I might want to implement various things directly in JavaScript or TypeScript and provide a Java API for it. But then I would need at least a tiny replacement for the `Generator` concept of the GWT. Is there a way to tweak or extend the JSweet compiler and tell that I want to write a custom logic to compile a class or interface from Java if it extends a specific base interface/class or has a specific annotation? I do not want to raise demands that will make JSweet as overengineered as GWT... So we can discuss that and maybe I also have to look for a solution outside JSweet that I can combine with JSweet then...

**Comment by renaudpawlak** [comment]
Well, let's proceed step by step and w.r.t. time available :) I have provided a proposal for #181 . Tell me if you are happy with it. ASAP, I will try to fix your other bugs. In any case, I believe that none of them have deep conceptual problems... they will just take time.

**Comment by renaudpawlak** [comment]
Hi @hohwille. I have good news. My last two commits should solve your problems, I have compiled your test project with the new snapshot and it works now. Hopefully we can now move forward to your objectives and see if you need more support :)
Thank you for helping improving JSweet!

**Comment by hohwille** [comment]
Awesome. I was kind of MIA but will come back into action very soon. Thank you so much!!! 👍
