### ISSUE TITLE
"(de)Serialization" of generic Javascript objects

### ISSUE THREAD

**Issue by Parakoopa** [cincheo/jsweet#188]
I'm sorry for the possibly completly wrong title, but I couldn't think of a better way to describe it.
Also this whole issue might be completely irrelevant for what JSweet is trying to do. I just thought I'd share my story and problems I ran into and maybe this might actually be a useful feature to add.

**What and why?:**
Currently it is rather complicated to deal with Typescripts "any" type objects at runtime and there is also no way of turning JSON parsed data into Java objects without much hassle.. 

Let's say there is some kind of object that may contain any sort of data. The typings in Typescript specify it as any, but in reality this is just a generic place to store any sort of typed data. We as the developer have to decide which data to store there, and we always know how the data might look like, depending on different situations/applications/implementations. Or we get any data via JSON and have to work without without really knowing which type it is.

My personal use case:
I'm working on a Java to Javascript Transpilation process using JSweet for the game Screeps. Screeps is a MMO RTS for programmers. The player codes a little colony of units and controls exactly what it does and how. And to store persistent data, there is a Javascript object called "Memory". This "Memory" object can contain any data I as a player want. I probably want to make it manageable and if I'm coding in Java I probably want to store real objects in it and read them again.

To make everything worse I can't even just throw the entire JSweet objects in there and hope to get them back and work with them because the whole Memory is JSON serialized.

Sure I could write complicated parsing mechanisms myself, but what if JSweet could actually detect the types of Javascript objects at runtime based on defintions I write in Java?

**Example / What I think would be great:**
Let's say we have a Javascript object like this:
```javascript
{
   "fieldA": 12,
   "fieldB": "lorem ipsum"
}
```
When working with it in JSweet this is either mapped using a class/interface or not. If not I have to deal with a raw jsweet.lang.Object myself. And I have no way of changing that besides touching the API.

But let's say we'd have some kind of class like this (not inside a def or Ambient but in the actual application!):
```java
public class Example implements jsweet.lang.Serializable {
    public int fieldA;
    public String fieldB;
   /* Constructors and Methods */
}
```
When using a object of this type inside my Java code I can write something like this which will convert this into a generic Javascript object:
```java
myExample.serialize();
```
This will then in JavaScript create a new object without any functions and only public (or anotated?) fields and a type description:
```javascript
{
   "__jsweet_type": "org.test.Example",
   "fieldA": 12,
   "fieldB": "lorem ipsum"
}
```
Using this information, this can safely be parsed back into a Java object:

```java
Object serialized = myExample.serialize();
if (Example.$matches(serialized)) {
    Example deserialized = Example.$parse(serialized);
}
```
where `$matches` is just an example for a helper method that checks if the types are actually compatible and if a "deserialization" can even be performed.

**This allows developers (not API creators!) to define own object types that can be serialized and transfered and stuffed into "any" type objects without to much understanding of the JSweet API or JavaScript.**

I hope you understand why this might be useful and I hope there's a way my idea can benefit the project :)

**Comment by Parakoopa** [comment]
One thing that just crossed my mind is that in this case there propably has to be some thought put into dealing with constructors. Classes like these probably would have to have no constructor, or at least support a constructor with no arguments to create the object.

**Comment by renaudpawlak** [comment]
Hi @Parakoopa. As you can imagine, this is a quite common scenario and we have implemented a solution for our projects. I am sharing the code [here](https://gist.github.com/renaudpawlak/4d1908a626ce2e0591c1a54bbe545ce5).

You can use it at will in your projects (that's public domain of course).

Your proposal on integrating this feature in the JSweet API is quite interesting, because it is a very common scenario that anyone will eventually face when using JSweet (or TypeScript anyways), and because the implementation is not that straightforward and requires a bit of knowledge about JSweet and JavaScript deserialization API. If we follow your idea, we would have:

1. A marker interface (jsweet.lang.Serializable?) or an annotation that would tell the transpiler to generate the ``__type`` field and initialize it with the class name *and* to check that the class provides an empty constructor.
2.  A helper method for JSweet-friendly deseralization. I don't think that the ``$matches`` method is that convenient. Remember that objects may have serialized referenced objects. It is better to have a transparent recursive approach with a handler (similarly to ``JSON.parse``). If the JSON structure does not contain the ``__type`` property, then it should just do nothing special and deserialize as usual.

The second point is the most problematic, because it would require a deserialization runtime. However, so far, JSweet does not have any runtime by default (it would go against the general approach). So, we could have support for 1 in the transpiler, and maybe provide 2 as a candy (some sort of deserialization lib). 

Another approach for 2 would be to integrate the deserialization feature in the generated code (like TypeScript providing the ``extend`` function). This approach would probably be better if we manage to make the deserialization code concise enough. (of course, it would be generated only when using the ``JSON.parse(xx)`` function). The cool thing about this approach is that it would be totally transparent to the programmers. They would just use ``JSON.parse(xx)`` as usual and the transpiler would automatically add the right JSweet deserialization handler to the generated code. (note that we should also provide this handler as a lib for interoperability purpose with TypeScript/JavaScript)
