### ISSUE TITLE
Calling method directly instead of arguments check

### ISSUE THREAD

**Issue by alievrenkut** [cincheo/jsweet#194]
Hi,

I like to ask for an enhancement if possible. Currently I am developing a application using JSweet which requires high performance. I think there can be an improvement for performance for methods that have same name but different arguments. JSweet compiles to code js with checks to find out which method is called by which arguments. I am guessing this can be changed to directly calling created method. For example:
method(int x, int y)
method(double x, double y)

this methods will be compiled into 3 methods 
method$int$int
method$double$double
method // which decides which method should selected

What I am suggesting is that when compiling java code JSweet can know which method will be called and call that method directly so no performance will be lost deciding at runtime.
This behaviour can be made optional. Also I am not saying remove method which decides because we will need it at calling from JS side.

Again thanks for this awesome project.

**Comment by renaudpawlak** [comment]
For sake of concision: "methods that have same name but different arguments" = overloaded methods.

Basically, you suggest that, when the compiler knows the actual types of the arguments, it tries to generate code that directly call the right method. This would indeed be possible for primitive types, final classes (such as String for instance), and enums maybe. For other types, it is probably not possible in the general case because the actual type may be a subtype.

I like your suggestion, however that's some work and it could take some time to implement and test in all cases. I will put it in the pipe and we will see when it will be possible to implement it.

In the meantime, I advise to avoid method overloading when high perf is required.

**Comment by renaudpawlak** [comment]
This is done in v2 :D
