### ISSUE TITLE
releases/snapshots and enum errors

### ISSUE THREAD

**Issue by nielsbaloe** [cincheo/jsweet#202]
Hi,

Thanks for jsweet, it's sweet ;) I'm trying to transfer my software vertx-ui from teavm to jsweet because TeaVM seems abandon-ware after no reply from some bug notifications. Here are some beginners questions.

First of all, I wonder why the jsweet-examples are using snapshots. It basicly means that they never work, at least not now and after a while. I've been struggling quite a while to get things going, trying to removing '-snapshot' until it works and those sorts of nonsense. That is really horror for first-time users. Please just bind examples to releases, snapshots are always terrible ;) Secondly the releases and snapshots don't match: there are jsweet-core releases in org.jsweet AND in org.jsweet.candies, and the last jsweet-core snapshot is older than the release (I would expect -SNAPSHOT releases to be the latest nightly build). Why distinguish two places (snapshots and release) for artifacts anyway? It's confusing to me, I don't know what to use.

Secondly I'm struggling with getting my code to work with enums. My virtual DOM uses enums for css-names, but the transpilers adds a few lines of code to my method that don't transpile. What's wrong here (see below: Java / typescript / error). There are some more errors, but this goes wrong about 10 times on similar code:

	public FluentHtml css(NameStyle name, String value) {
		if (styles == null) {
			styles = new HashMap<>();
		}
		styles.put(name, value);
		if (element != null) { // note: nameStyle() = NameStyle.name() with some exceptions
			element.style.setProperty(nameStyle(name), value);
		}
		return this;
	}
	
    public css(name? : any, value? : any) : any {
            if(((name != null && name instanceof live.connector.vertxui.fluentHtml.NameStyle) || name === null) && ((typeof value === 'string') || value === null)) {
                return <any>(() => {
                    if(this.styles == null) {
                        this.styles = new HashMap<any, any>();
                    }
                    this.styles.put(name, value);
                    if(this.element != null) {
                        this.element.style.setProperty(FluentHtml.nameStyle(name), value);
                    }
                    return this;
                })();
            } else if(((name != null && name instanceof live.connector.vertxui.fluentHtml.NameStyle) || name === null) && value === undefined) {
                return <any>this.css$live_connector_vertxui_fluentHtml_NameStyle(name);
            } else throw new Error('invalid overload');
        }

2016-12-24 16:19:23.023 INFO  JSweetTranspiler:1081 - live/connector/vertxui/fluentHtml/FluentHtml.ts(237,50): error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.

Thanks!
NielsBaloe

**Comment by renaudpawlak** [comment]
Hi.

First a little preamble. JSweet and TeaVM are quite different approaches because TeaVM aims at emulating Java. JSweet is Java flavor, but it is meant to program actual JavaScript applications. It is very similar to TypeScript. Of course, JSweet supports more and more Java constructs (and it will probably improve along the way), but don't expect JSweet to be able to compile all legacy Java code. Some will work fine, but some will raise issues. In that case, I am more than happy if you report bugs, but you may need to slightly adjust your code in the meantime: some fixes may take some time, and some may even be impossible without breaking JavaScript interoperability. For a full Java support you may want to bet on J2CL, which is an approach similar to TeaVM.

What it the point of JSweet? Well, JSweet being very close to JavaScript, it is fully interoperable with it and it is easy to use JSweet in JavaScript applications or libraries. If you don't plan to use any JS libs at all and want only to use Java libs, you should probably consider looking somewhere else in the short term.

Back to the issues. The snapshots in the candies (JS libs) are for historical reasons. Candies are automatically generated from TypeScript and we decided to publish them as snapshots because the original TypeScript files were moving all the time. We did a couple releases following the transpiler releases. Looking back, that process appears to be suboptimal and quite difficult to maintain, so we are currently changing it. Coming with JSweet version 2 (WIP), all candies will now be independant and follow their own release cycle. Also, candies will become much more independent from the transpiler releases. Note also that because we are reorganizing the artifacts to prepare version 2, it could explain some apparent inconsistencies in the artifact timestamps.... 

So... all these issues should be fixed soon with version 2.

Regarding your compilation problems, it appears that I don't have enough info to fully understand it. First make sure that you use the transpiler version 1.2.0 (and the associated Maven plugin). If the errors occur on that version, then please isolate the exact line in the generated TypeScript code and report it by showing:

1. the original Java code 
2. the generated TS code (showing the lines the errors refer to) 
3. the errors (you may want to show more than one error) 

Thanks in advance.

**Comment by nielsbaloe** [comment]
Hi!

Thanks for your great reply!!

Well, jsweet looks fine to mee too!! I have zero legacy code, I'm writing new code, combining vert.X and native java GUI , see https://github.com/nielsbaloe/vertx-ui  . I don't have any troubles leaving out some java constructs and rewriting some code myself instead of using libraries - actually I have been doing that for teavm too. For example I wrote stream stuff (synchronously with arraylists) because teavm doesn't support it. Don't think that teavm is that better in parsing java code, I'm stuck now because there are problems with lambda's, and without lambda's it's going to get pretty 2010.

OK, I see the historical reasons regarding snapshots/releases, good to know. No worries.

Actually, I already provided exactly what you ask for: the original java code, the generated TS and the errors (which did not format properly perhaps). They are all there. Can you please take another look?

Thanks!
Niels

**Comment by renaudpawlak** [comment]
I might be missing something. Do you want me to try to compile https://github.com/nielsbaloe/vertx-ui? From you initial post, I think I miss the Java code that generates the given TS code, and I miss also the line numbers in the TS code so that I can see the exact place of the error. That said I can try to compile the entire project, but that will take me some time to fix the bugs anyways, because I have limited time during vacation :)

**Comment by renaudpawlak** [comment]
One last thing... please double check your JSweet version... I am pretty sure that I fixed some very similar issues with enums and overloadings in the last version... If you are not sure what version you are using, please just check the first line of the generated TS file. It should say 1.2.0 (snapshot or not). If it says 1.1.x, then it is why you are having all your problems.

**Comment by nielsbaloe** [comment]
Hi!,


Hmm, yes I'm using JSweet 1.2.0. I didn't overload enums, that was not possible but that's fine.


You don't need to compile anything. You can see the java code, the ts code and the compile error in my original e-mail, or otherwise peek at https://github.com/cincheo/jsweet/issues/202 or below.


Thanks!

Niels


>---


java/ts/error:

public FluentHtml css(NameStyle name, String value) {
        if (styles == null) {
                styles = new HashMap<>();
        }
        styles.put(name, value);
        if (element != null) { // note: nameStyle() = NameStyle.name() with some exceptions
                element.style.setProperty(nameStyle(name), value);
        }
        return this;
}

public css(name? : any, value? : any) : any {
        if(((name != null && name instanceof live.connector.vertxui.fluentHtml.NameStyle) || name === null) && ((typeof value === 'string') || value === null)) {
            return <any>(() => {
                if(this.styles == null) {
                    this.styles = new HashMap<any, any>();
                }
                this.styles.put(name, value);
                if(this.element != null) {
                    this.element.style.setProperty(FluentHtml.nameStyle(name), value);
                }
                return this;
            })();
        } else if(((name != null && name instanceof live.connector.vertxui.fluentHtml.NameStyle) || name === null) && value === undefined) {
            return <any>this.css$live_connector_vertxui_fluentHtml_NameStyle(name);
        } else throw new Error('invalid overload');
    }


2016-12-24 16:19:23.023 INFO JSweetTranspiler:1081 - live/connector/vertxui/fluentHtml/FluentHtml.ts(237,50): error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.


________________________________

**Comment by renaudpawlak** [comment]
Not enough time to deal with this in the context of 1.2. Re-open if still a problem with upcoming v2.
