### ISSUE TITLE
un-wanted package prefix added

### ISSUE THREAD

**Issue by lancemao** [cincheo/jsweet#207]
Hey guys,

imagine we have business Java code which is in package:
com.mycompany.java (the key is the unusual 'java' folder)
and we have somehow injected java.io.FileInputStream class into our JSEngine

when using our FileInputStream, we clearly imported:
import java.io.FileInputStream;
we didn't import com.mycompany.java.io.FileInputStream

the bug happens when we run JSweet to convert our Java to JS which added un-wanted package prefix before java.io.FileInputStream, i.e.
mycompany.java.io.FileInputStream

we believe this happens because as jsweet searches com.mycompany, and found 'java' is a sub folder under mycompany, so it assumes any class under java should be under mycompany, which in most cases is correct except when someone injected 'java' before converting business code

Hope the community take a look at this issue ASAP since our life and career depends on this awesome tool. we have somehow 'proved' to our boss that jsweet is our best ally on his next huge project

**Comment by renaudpawlak** [comment]
Hi,
I was not able to reproduce the issue. Could you be more specific on how to reproduce? Are you using JSweet Maven plugin version 1.2.0?
The easiest would be to set up a project with a couple classes showing the issue.
Have you looked how J4TS packages java.* files?

**Comment by lancemao** [comment]
[TestBundle1.zip](https://github.com/cincheo/jsweet/files/707111/TestBundle1.zip)

we have attached a simple test project to reproduce this issue. please take a look, thanks

**Comment by renaudpawlak** [comment]
Thanks but it looks like this project is missing JSweet configuration. How am I supposed to transpile with JSweet? Could you make sure that I can compile with Maven or Gradle? Thanks.

**Comment by lancemao** [comment]
Our gradle file contains much of other code which should be useless for this issue. The transpiling part is simple, we downloaded JSweet related jars, wrapped with our own J2SE code to start it. like this:
```
JSweetTranspiler transpiler = new JSweetTranspiler(tsOutputDir, jsOutputDir, null, classPath);
transpiler.transpile(transpilationHandler, sources.toArray(new SourceFile[0]));
```

**Comment by renaudpawlak** [comment]
Sorry for the delay but I was pretty busy. I appreciate that you have built your own JSweet launcher but it does not help to test things. Plus it could be that you meet issues that are related to your launching method... If you could use the Gradle plugin to compile, it would certainly help (https://github.com/lgrignon/jsweet-gradle-plugin). I you need it to be updated for JSweet latest version I am sure it can be done.

Anyway, I still don't see the problem because when I look at the generated code of the TestBundle1.zip you sent (target/bundle.js), I see the following code, which does not look wrong to me (I may be missing the point again though).

```typescript
/* Generated from Java with JSweet 2.0.0-SNAPSHOT - http://www.jsweet.org */
namespace com.huawei.android {
    export class Test {
        public test() {
            let bundle : android.os.Bundle = new android.os.Bundle();
        }
    }
    Test["__class"] = "com.huawei.android.Test";

}
/* Generated from Java with JSweet 2.0.0-SNAPSHOT - http://www.jsweet.org */
namespace com.huawei.test {
    /**
     * Created by lvghua on 17/1/9.
     */
    export class TestError {
        public test() {
            let bundle : android.os.Bundle = new android.os.Bundle();
        }
    }
    TestError["__class"] = "com.huawei.test.TestError";

}
```

So can you tell me what the problem is with that code?

**Comment by lancemao** [comment]
At first, we transpile Java into very plain Javascript code, no TS, no commonJS. After play with the parameters, we found out two interesting modes:
```
1. transpiler.setModuleKind(ModuleKind.commonjs); // fix our problem and boost performance
2. transpiler.setBundle(true); // problem still exists
```

I think we will head to option 1. And thank you very much for your support. We are very confident that JSweet will do the trick

**Comment by renaudpawlak** [comment]
Well, I still don't get it, but fine :)
AFAIK, the commonjs mode is good when using a node.js module system in node.js or in the browser (in frameworks such as Electron or Angular 2 for instance). The bundle mode is a convenient way to develop classical browser applications and JSweet takes care of the JavaScript ordering for you. These imply two different technical contexts. Although possible, you should not use the bundle option when working with node.js modules because it would be much more efficient (in terms of performances) to let the module system load the files when requested (with the bundle option, all your code gets loaded upfront, which can be slow). So, generally speaking, try using modules when your application code will get big, because it is better for scalability.

Please don't hesitate to tell me if you run into problems. I can help but I'll probably need more detailed information in that case.

**Comment by lancemao** [comment]
thanks for your comments. We've got one more question regarding commonjs. Say in our main java file, we want to import a class from another package, JSweet translate like this:
`var MyAdapter_1 = require("../adapter/MyAdapter");`

and when we create an new instance, JSweet translates:
`var myAdapter = new MyAdapter_1.MyAdapter();`

In MyAdapter, we already define a proper Java class and JSweet translates with commonjs style:
```
var MyAdapter = (function () {
    return MyAdapter;
};
exports.MyAdapter = MyAdapter;
```

my question is, why we need _1 suffix? why not just directly go like this:
```
var MyAdapter = require("../adapter/MyAdapter");
var myAdapter = new MyAdapter();
```
and in MyAdapter definition, directly exports:
`exports = MyAdapter;`

I understand this way, exports can store only one class, but isn't that always the case when dealing with Java class? 
The current approach works fine, but to have bunch of '_1' in our code makes me uneasy. Could there be '_2', '_3'? I think I'm missing something here?
Or can JSweet provide an option to remove '_1'?

**Comment by renaudpawlak** [comment]
Well... I don't remember exactly why I added the suffix :(
My guess would be to avoid clashes when importing several classes having the same name from different modules. However, it might be unnecessary (because Java prevents it anyway) or could at least be improved...

We need to work a little bit on "require" for version 2. Hopefully I will have time to take a look at it, but this is not a priority so it is unlikely in the short term.

Remember: it's open source and PRs are welcome ;) You may want to create a new issue if you fell it's important.
