### ISSUE TITLE
How to make node js http request?

### ISSUE THREAD

**Issue by liaotianr** [cincheo/jsweet#209]
How can I use the first sample code given at https://docs.nodejitsu.com/articles/HTTP/clients/how-to-create-a-HTTP-request/ in my JSweet application?

I added the nodejs candy to my dependencies but I don't know how to make a simple http request with JSweet and nodejs. 

Can someone please provide an example to me?

I looked at the [node js / jsweet sample repository](https://github.com/lgrignon/jsweet-node-example) that was linked on the website but it's a bit overwhelming to me.

**Comment by renaudpawlak** [comment]
Well, it's true that this sample is quite hard to start with. If you want to start from the basic quickstart, first you need to unable the commonjs modules (add ``<module>commonjs</module>`` in the configuration section). Then include the node.js candy and I think that you are supposed to use the Globals class of the http package: http://public.jsweet.org/apidocs/snapshots/org/jsweet/candies/node/6.0.0-SNAPSHOT/def/node/http/Globals.html. Finally, you should run your program with node (of course).

However I am not sure because I have never tried it. I think that a JSweet node quick start would be a good thing...

**Comment by liaotianr** [comment]
Thanks for your reply.

It seems I need to use `def.node.https.Globals.request(requestOptions, consumer);` that accepts a `RequestOptions` object and a `Consumer<IncomingMessage>`. 

But I cannot find any implementation of [RequestOptions](http://public.jsweet.org/apidocs/snapshots/org/jsweet/candies/node/6.0.0-SNAPSHOT/def/node/http/RequestOptions.html) as it is an abstract class. Am I supposed to write a class that implements RequestOptions by my own?

**Comment by renaudpawlak** [comment]
In JSweet RequestOptions is an interface definition to apply typing to an object structure. It is used like this:

```java
new RequestOption() {
    {
        method = "PUT";
        hostname = "jsweet.org";
        path = "myPath";
    }
};
```

It is transpiled to:

```java
{
    method : "PUT";
    hostname : "jsweet.org";
    path : "myPath";
};
```

**Comment by liaotianr** [comment]
Imports:
```
import static def.node.https.Globals.request;
import def.node.http.ClientRequest;
import def.node.https.RequestOptions;
```
...


		RequestOptions options = new RequestOptions() {
			{
				method = "POST";
				hostname = "google.com";
				path = "/";
			}
		};

		ClientRequest cr = def.node.https.Globals.request(options);

Highlighting my class name in Eclipse shows the following errors:
- Cannot find namespace 'http'
- Cannot find namespace 'https'
- Cannot find name 'https'

**Comment by liaotianr** [comment]
I'm also wondering if I'm setting up the callbacks in a correct way. I make use of JSweets `Function` class.

```
		RequestOptions options = new RequestOptions() {
			{
				method = "POST";
				hostname = "example.com";
				path = "/news";
			}
		};

		ClientRequest cr = request(options);
		
		Function onNewMsg = new Function() {
			@Override
			public Void apply(Object thisArg) {
				System.out.println("Receiving data chunk: "+(String) thisArg);
				return null;
			}
		};
		
		Function onEndMsg = new Function() {
			@Override
			public Void apply(Object thisArg) {
				System.out.println("Data received");
				return null;
			}
		};
		
		cr.on("data", onNewMsg);
		cr.on("data", onEndMsg);
		cr.write("field=value");
		cr.end();
```

**Comment by renaudpawlak** [comment]
Couple things:
- From what I see in the Node.js API, I am usure how to use the Node.js http functions. I suspect a problem in the API because of modules (it has already been the case often in the past for other candies than Node.js), but I have not used Node.js personally because I use Java on the serveur side. So, I think that the best would be to ask to @lgrignon who wrote the Node.js example. I'll prompt him for feedback.
- In JSweet, the best way to write a callback is to write a Java 8 lambda (functional types). The ``jsweet.lang.Function`` class is the JavaScript Function object... as such it is not typed...  Below a good way to define/use callbacks with JSweet:

```java
Consumer<String> onNewMsg = (thisArg) -> {
				System.out.println("Receiving data chunk: "+thisArg);
			};
```

If the API expects a Function object rather than a lambda/functional type, you can use the ``jsweet.util.Globals.function`` helper, which transforms a functional type to a Function object:

```java
import static jsweet.util.Globals.function;
...
cr.on("data", function(onNewMsg));
```

**Comment by renaudpawlak** [comment]
Ok. I had some time to take a closer look.

This works (I have juste tested it):

```java
package quickstart;

import static def.node.https.Globals.request;

import def.node.http.ClientRequest;
import def.node.https.RequestOptions;

public class QuickStart {

	public static void main(String[] args) {

		RequestOptions options = new RequestOptions() {
			{
				method = "POST";
				hostname = "google.com";
				path = "/";
			}
		};

		ClientRequest cr = request(options);
	}

}
```

WARNING: if you are using the JSweet Eclipse plugin, you need also to select the commonjs module kind:

Right click on project >  Properties > JSweet > Module Kind (select commonjs)

**Comment by liaotianr** [comment]
> WARNING: if you are using the JSweet Eclipse plugin, you need also to select the commonjs module kind [..]

That was a good hint. Before I just inserted it in my pom.xml.

Now I'm only struggling around with the callbacks.

```
package quickstart;

import static def.node.https.Globals.request;
import static jsweet.util.Globals.function;

import java.util.ArrayList;
import currency.CurrencyCode;
import currency.CurrencyPair;
import def.node.http.ClientRequest;
import def.node.https.RequestOptions;
import jsweet.util.function.Consumer;



public class QuickStart {

	public static void main(String[] args) {

                String incomingData = "";

                RequestOptions options = new RequestOptions() {
			{
				method = "POST";
				hostname = "google.com";
				path = "/";
			}
		};

		ClientRequest cr = request(options);
		
		Consumer<String> onNewMsg = (thisArg) -> {
			incomingData = incomingData+(String) thisArg;
		};
		
		Consumer<Void> onEndMsg = (Void v) -> {
			System.out.println("Data received");
		};
		

		cr.on("data", function(onNewMsg)); 
		cr.on("data", function(onEndMsg));
		cr.write("field=val");
		cr.end();

	}

}
```


```
The method function(Runnable) in the type Globals is not applicable for the arguments (Consumer<String>)
Quick fix suggestions:
Add static import for 'Globals.function'
```

Eclipse is not satisfied with the function(onNewMsg) and function(onEndMsg) call. But actually the function method should accept `Consumer<String>` objects.

Furthermore the `onEnd` callback of nodejs should not have any parameters. But removing it leads to another error.

As you can see in the imports `jsweet.util.Globals.function` is already imported and a click on the Quick fix does not solve the problem either.

**Comment by renaudpawlak** [comment]
Don't use functional types in ``jsweet.util.function.*``, I need to deprecate those... Just use standard Java functional types. Basically, replace: ``import jsweet.util.function.Consumer;`` with ``import java.util.function.Consumer;`` and it should fix your problem.

Also, prefer ``Runnable`` over ``Consumer<Void>``.

```java
		Runnable onEndMsg = () -> {
			System.out.println("Data received");
		};
```

**Comment by liaotianr** [comment]
Thanks again. I noticed I cannot use the commonjs module and the bundle feature together. Does that mean I need to manually include all my .js files again?

The build was successful after I removed <bundle>true</bundle>.

`ERROR: bundle and module options are exclusive: choose one or the other`

**Comment by renaudpawlak** [comment]
When you use the module options, it uses ``require`` to automatically import your files. So all you need to do is to run your entry point with Node and the other files that are required should be imported automatically. That's why the bundle option is useless when using modules.

**Comment by liaotianr** [comment]
Okay I understand. My project compiles fine but when I run my app I'm getting `Cannot find module '../cars/CarCode'`. My build log clearly says that the corresponding js file was created. I didn't get this error when I was using the bundle feature.

I should note that CarCode is a simple enum.

`public enum CarCode {
	X1, X2, X3	
}`

**Comment by renaudpawlak** [comment]
:(

I have tried various configurations (classes and enum in same or different packages), but it works fine for me.

Maybe you can check the generated code to track something wrong with the generated js. Or you can send me some code that fails so that I can try to look closer.

**Comment by liaotianr** [comment]
I just sent you an email with the attached sample code to reproduce the error.

**Comment by renaudpawlak** [comment]
Your email address seem to fail so I am answering here...

Hi! Ok I have run the program with the following command:

```bash
$ node target/js/quickstart/QuickStart.js 
```

Which gives me the error: Error: Cannot find module 'jQuery'

Fine, I install jQuery with "npm install jquery" and run again.

Which gives a new error: ReferenceError: java is not defined

That's because you are using java.util.ArrayList. This is potentially a problem because J4TS is compiled as a browser bundle and should be compiled as Node module first.

I am surprised though because you did not mention this problem. Maybe because you are running with Electron...

So, I decided to do a last test by removing all the ``java.util.ArrayList`` and changing them to ``jsweet.util.Array``. I run again and this gives me the following trace:

```
Kraken init
Kraken init
Kraken
/Users/renaudpawlak/git/jsweet-quickstart/node_modules/jquery/dist/jquery.js:31
					throw new Error( "jQuery requires a window with a document" );
					^

Error: jQuery requires a window with a document
    at module.exports (/Users/renaudpawlak/git/jsweet-quickstart/node_modules/jquery/dist/jquery.js:31:12)
    at Function.QuickStart.main (/Users/renaudpawlak/git/jsweet-quickstart/target/js/quickstart/QuickStart.js:27:9)
    at Object.<anonymous> (/Users/renaudpawlak/git/jsweet-quickstart/target/js/quickstart/QuickStart.js:56:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

Which makes sense because I am running with node and you cannot use jQuery in node.

So, from what I understand, you are running you app with Electron, which looks really cool but it probably comes with a whole environment on the top of node.js. So I need to run with Electron if I want to do exactly like you do. (btw I did not know electron but I think that's looks like a really good target environment for JSweet).

I don't think you need to share the whole app, but could you share the command and potential configuration for running with Electron? Btw, maybe it is just the way you run with electron that poses problem (?)

**Comment by renaudpawlak** [comment]
Fixed. @liaotianr if you want to share your solution.

**Comment by liaotianr** [comment]
Sharing is caring :) My "cannot find module.." problem in my nodejs/Electron environment disappeared after I used require() to include my javascript into the html page. In my case I replaced

`<script type="text/javascript" src="../target/js/quickstart/QuickStart.js"></script>`

with

`<script> require("../target/js/quickstart/QuickStart“); </script>`

in my index.html.
