### ISSUE TITLE
Prefix non-public members with '__'

### ISSUE THREAD

**Issue by alievrenkut** [cincheo/jsweet#219]
Hi, I like to ask for a new feature. Is it possible to add an option for transpiling to TS/JS to add '__' or any other prefix to all non-public members of a class so API users can know that they should not use these members directly. Now there is no easy separation in JS. Thanks.

**Comment by renaudpawlak** [comment]
Actually, believe it or not, but it is the sort of feature that is quite "straightforward" to add with JSweet 2 (use the 2.0.0-SNAPSHOT). As you may know, JSweet defines a ``@jsweet.lang.Name`` annotation that allows the user to override the Java name of a program element (so that it uses the annotation's value instead of the Java element name). 

Also, since version 2, JSweet allows the user to tune the transpiler's behavior thanks to the factory. The factory can create subclasses of the transpiler main components :) In your case, it is possible to extend the factory to create a subclass of the context. The context is the component where JSweet will lookup the annotations at compile time. So, you can just override two methods to implement the behavior you want here. Here is how it should look like:

```java
[...]
// the @Erased annotation tells JSweet not to transpile this class, so it is only seen from Java
@Erased
public class PrefixNonPublicMembersJSweetFactory extends JSweetFactory<JSweetContext> {

	@Override
	public JSweetContext createContext(JSweetOptions options) {
		return new JSweetContext(options) {
			// a symbol is a named compile-time Java program element
			private boolean isNonPublicMember(Symbol symbol) {
				return (symbol instanceof VarSymbol || symbol instanceof MethodSymbol)
						&& symbol.getEnclosingElement() instanceof ClassSymbol
						&& !symbol.getModifiers().contains(Modifier.PUBLIC) && Util.isSourceElement(symbol);
			}

			@Override
			public boolean hasAnnotationType(Symbol symbol, String... annotationTypes) {
				if (ArrayUtils.contains(annotationTypes, "jsweet.lang.Name") && isNonPublicMember(symbol)) {
					return true;
				} else {
					return super.hasAnnotationType(symbol, annotationTypes);
				}
			}

			@Override
			public String getAnnotationValue(Symbol symbol, String annotationType, String defaultValue) {
				if ("jsweet.lang.Name".equals(annotationType) && isNonPublicMember(symbol)) {
					return "__" + symbol.getSimpleName();
				} else {
					return super.getAnnotationValue(symbol, annotationType, defaultValue);
				}
			}
		};
	}

}
```

Then, in the JSweet Maven plugin configuration of your pom.xml, you just need to tell JSweet to use your factory instead of the default one by adding the following option:

```xml
<factoryClassName>path.to.factory.PrefixNonPublicMembersJSweetFactory</factoryClassName>
```

Note that if you package your JSweet factory in an external Maven projet, you will have to add a dependency in the optional ``dependencies`` section of the JSweet Maven plugin. Of course, version 2 is still under development and the API may still move a little. Also, there is no document for it yet (except for the source code). But if you want to try it out and tell me if it works for you, that would help.

**Comment by alievrenkut** [comment]
Thanks for very detailed answer. I prefer the second option. I will try it when I migrate to 2.0.0-SNAPSHOT which I don't know when. I will let you know the result for sure after migration.

Is there a target date for stable 2.0 version?

**Comment by renaudpawlak** [comment]
I wish I would know the date... But the snapshot is already quite advanced but there are still improvements to be made in the API so I cannot promise anything so far :(

**Comment by renaudpawlak** [comment]
I have added a composable [adapter](https://github.com/cincheo/jsweet/blob/master/transpiler/src/main/java/org/jsweet/transpiler/extensions/AddPrefixToNonPublicMembersAdapter.java) to implement this feature in version 2. Note that the extension API has been simplified a little bit. 

In order to activate it, you need to create a factory that instantiates that adapter, and then make sure that you use this factory in the pom.xml:

```java
public class MyPrefixAdderFactory extends JSweetFactory {
	@Override
	public Java2TypeScriptAdapter createAdapter(JSweetContext context) {
		return new AddPrefixToNonPublicMembersAdapter(super.createAdapter(context));
	}
}
