### ISSUE TITLE
transpiler release poms need to have non snapshot dependencies

### ISSUE THREAD

**Issue by desolate-planet** [cincheo/jsweet#229]
I work within an environment which does not allow snapshot builds for third party software. This was no problem initially as we could see you have a release-local repo for the jsweet-transpiler, but on further inspection of the poms (after getting several errors), I found that your dependencies are still snapshots rather than release artifacts. Is there a reason for this (in which case, I could argue allowing snapshot libs) or is it an omission?

**Comment by renaudpawlak** [comment]
Hi. Yes, it was on purpose at the beginning because automatically translated candies would be updated daily. Note that we did some releases too that you may find on our repo (depending on which candy you need). But released candies may be outdated. With JSweet 2, a set of cleanly released candies should be maintained, but so far, I would allow your env to work with snapshots because you may hit limitations otherwise.
