### ISSUE TITLE
Function named 'apply' does not transpile

### ISSUE THREAD

**Issue by foopq** [cincheo/jsweet#238]
Hello, I'm finding that functions named 'apply' will not transpile correct. For example, using the live sandbox, if I have the following:

`static public int apply(String a) {
        return 0;
}`

it will create the following TypeScript (function name is missing):

`public static (a : string) : number {
            return 0;
}`

**Comment by renaudpawlak** [comment]
That's because ``apply`` is a reserved method name in JSweet to define callable objects (anonymous functions in TypeScript). Initially it was supposed to be possible to call a method ``apply`` using a ``@Name("apply")`` annotation, but it does not seem to work anymore (probably a regression). In any case, that's not really intuitive because ``apply`` is a commonly used method name in Java. I believe we should fix and change this behavior for version 2. Here's what would be the plan.

1. the reserved function name for anonymous functions should be ``$apply`` (that's more consistent with other JSweet conventions such as ``$new``).
2. we should fix the bug of the ``@Name`` annotation (i.e. defining a function named ``$apply`` should work by annotating a function with ``@Name("$apply")``
3. We should define an ``@Anonymous`` annotation in order to have any Java method (other than ``$apply`` be anonymous) 
4. we should have more complete tests on that feature to avoid potential regressions.

Practically speaking, it means that in v2, you will be able to use ``apply`` as a function name. In order to define anonymous functions, you should just annotate them with ``@Anonymous`` (which can be used to annotate existing ``apply`` methods for backward compatibility). 
If everybody is ok with this, I will plan this for v2.

Thanks for reporting!

**Comment by lgrignon** [comment]
I will try to take a look at this tonight.

Thanks for bringing that up.

**Comment by renaudpawlak** [comment]
This should now work when using JSweet v2 and new candies... Not for all cases so we leave it open though...
