### ISSUE TITLE
Build instructions 

### ISSUE THREAD

**Issue by davidmoten** [cincheo/jsweet#24]
I did `mvn install` and build failed due to the absence of an executable `pandoc`, `node`. 

Can you document the build instructions/dependencies in the README.md please. 

All seemed to work for me after I did the following:

```
sudo apt-get install pandoc nodejs
## sort out an executable name conflict with another package by opting for nodejs
sudo ln -s /usr/bin/nodejs /usr/bin/node
```

**Comment by renaudpawlak** [comment]
David, I have removed the pandoc generation from the pom.xml (it had nothing to do there) so that pandoc is not required to build the project anymore. I have also added a "How to build" section in README.md to make all this as clear as possible.

Regarding the nodejs issued, I have not met it myself, so I added a link in the readme file. Do you think that it would be possible that JSweet supports both node and nodejs command names so that it limits this kind of issue?

**Comment by davidmoten** [comment]
Thanks @renaudpawlak, changes to the doco look fine to me and are sufficient I think (I wouldn't add support for both `node` and `nodejs` executable names without more convincing use cases than this).
