### ISSUE TITLE
Runnable converted to () => void, causing error

### ISSUE THREAD

**Issue by chrismiddleton** [cincheo/jsweet#249]
I have a Runnable.java:

	package java.lang;

	public interface Runnable {
		public void run ();
	}

a Thread class with this constructor:

	public Thread (Runnable target) {
		this.target = target;
	}

and a class that uses it:

    class Foo {
        public void bar () {
            Foo f = new Foo();
            new Thread(f);
        }
    }

(The above is a simplification of the Foo class, obviously.)

When it compiles to TS, I get this error:

    2017-04-18 13:38:39.039 INFO  JSweetTranspiler:1250 - Foo.ts(55,76): error TS2345: Argument of type 'Foo' is not assignable to parameter of type '() => void'.
    2017-04-18 13:38:39.039 ERROR output:48 - argument of type 'Foo' is not assignable to parameter of type '() => void' at Foo.java(59)

And the generated TS shows this:

    public constructor(target : () => void) {
        this.target = null;
        this.target = target;
    }

Why did the Runnable argument get converted to `() => void`? Is there a workaround or should I do it a totally different way? My primary goal is to get my existing Java code to compile, even if the lack of real threads in JS means I have to then change the resulting JS code around.

**Comment by renaudpawlak** [comment]
Ok. This one was tough.

The point is that in Java, lambdas have a dual nature. They are functions which are implemented with objects, or they are objects that can be used as functions (depending on which angle you look at it).

Since JSweet was initially made to map TypeScript, the choice was made to map functional types to lambdas (and not to objects). So ``Runnable`` is mapped to ``() => void``, ``Consumer<String>`` is mapped to ``(string) => void``, and so on.

This is fine when using lambda expressions in Java or when constructing anonymous classes out of functional types. It gets trickier when building implementations of functional interfaces, which are regular classes, having regular instances, but with can be used in place of lambdas. It is OK in Java, but not in TypeScript because a functional type is not an object type and conversely.

In order to allow this, I had to relax typing when passing objects types to functional types and add a runtime check to allow the program to call the right method when applying on an object rather than an actual function.

This is still compatible with the old way, but it complexifies the generated code a little bit unfortunately. The good point is that it improves interoperability between JSweet-compiled Java code and JavaScript.

Anyway, the problem you describe should now be OK with the current snapshot. Don't hesitate to tell me if it works or not.

Thanks again for you help!

**Comment by chrismiddleton** [comment]
You deserve a medal. I will check it out to confirm and let you know.

**Comment by chrismiddleton** [comment]
I've confirmed that this is no longer causing an error, and although I haven't run it yet, the output looks correct. Awesome work!
