### ISSUE TITLE
ClassHelper does not exist on internal

### ISSUE THREAD

**Issue by chrismiddleton** [cincheo/jsweet#256]
This code:

    ourApplet = (Applet) Class.forName(className).newInstance();

gets translated to this in TS:

    this.ourApplet = <any>javaemul.internal.ClassHelper.forName(className).newInstance()

but I get this error on that line

    Property 'ClassHelper' does not exist on type 'typeof internal'

My pom.xml versions if it's helpful:

- maven-compiler-plugin: version 3.1, source 1.8, target 1.8
- jsweet: 2.0.0-SNAPSHOT
- jsweet-maven-plugin: [1.0.0,)
- jsweet-core: 1.2.0-SNAPSHOT
- j4ts: 0.3.0-SNAPSHOT
- jquery: 1.10.0-SNAPSHOT

**Comment by renaudpawlak** [comment]
Well, J4TS is so far not very-well tested with JSweet 2. Plus there are still missing APIs. I am not surprised that reflection is not supported (it will probably never be fully supported).

The good news though is that having a simple (but working) implementation of ``forName`` and ``newInstance`` is fairly easy. As shown in this [commit](https://github.com/cincheo/jsweet/commit/746ed2a6c3cccd15858be2b802b52ae5df4f7f3f) have implemented it when J4TS is not used, so it should work if you remove J4TS from your classpath. Note that if you look at the code needed, you should see that it was a quite simple implementation.

If you can, I would advise to try to remove J4TS from your classpath anyway and use JSweet 2 in the default mode (without runtime).

I keep this issue open because I think that J4TS should be improved to support ``forName`` and ``newInstance``. That's more a J4TS issue but right now it still need to be update for JSweet 2.

**Comment by renaudpawlak** [comment]
`Class.forName` is now supported by default in JSweet v2.

**Comment by renaudpawlak** [comment]
(as well as `Class.newInstance` btw... with some systemic limitations)
