### ISSUE TITLE
Double.valueOf causing syntax errors in TS output

### ISSUE THREAD

**Issue by chrismiddleton** [cincheo/jsweet#260]
I'm guessing that this is due to a recent change, maybe for one of the fixes for an issue I raised recently. When I did a `mvn install`, the new version of 2.0.0-SNAPSHOT is generating syntax errors relating to `Double.valueOf`.

Previously the code generated this JS:

    var mmRes = javaemul.internal.DoubleHelper.valueOf(nameStr);

(I don't have the TS still.)

But now the TS looks like this:

    let mmRes : number = /* doubleValue */parseFloat(nameStr)javaemul.internal.DoubleHelper.valueOf(nameStr);

It looks like it's trying to apply both parseFloat AND the javaemul thing.

The error is this:

    2017-04-21 12:27:06.006 INFO  JSweetTranspiler:1262 - bundle.ts(1832,90): error TS1005: ',' expected.

It looks like it caused a cascade of errors in my bundle (381 errors) so I'm not sure if this is the only issue, but my guess is that it is.

This issue only occurs when I remove j4ts from my build (as was suggested to solve a different problem).

Thank you for all your work.

**Comment by renaudpawlak** [comment]
I have made a quick fix on this issue because it was a really silly mistake (you can check the commit). Hopefully it will work now.

You have to know that if you remove J4TS, JSweet will try to replace all Java with pure JS code (with some sort of macros). When JSweet does not how to replace Java code with JS code, it will fallback to J4TS emulation (typically ``javaemul.internal`` helpers), but since it is not there, it will raise compilation errors.

So you may hit other errors when compiling without J4S, but although the number of compilation errors may be impressive, all these errors are usually quite easy to fix and I am willing to take the time to fix them because other people will benefit these fixes (most of the time, it is just a matter of supporting a new Java function). So don't hesitate to send me the errors you get until we fix them all :)

If you don't have time for this, you tell me and we can go back with J4TS.

**Comment by chrismiddleton** [comment]
Wow, you are so fast at fixing these things. +1000. That fix does look like it would do it, but after doing a `mvn install`, I don't see any difference yet in my compile (still getting the errors). When a fix like this is made, does it auto update the snapshot or is that a manual process for the snapshot to get updated? Not trying to rush things, just curious.

**Comment by renaudpawlak** [comment]
We have an automatic deploy process. But the tests are quite long to pass. Normally it is already deployed.
So, you might need to force the snapshot to update with the right Maven option (I noticed that the snapshots update not immediately), or by cleaning your Maven local repo.

**Comment by chrismiddleton** [comment]
Thanks for the info and the tip. Either waiting or doing `mvn clean install -U` seemed to do the trick. I have a different error now but I think that fixed that one.
