### ISSUE TITLE
Transpile back to Java from JavaScript

### ISSUE THREAD

**Issue by giridhar2015** [cincheo/jsweet#264]
Hi,

I have big JavaScript file which is transpiled from Java using JSweet. Since this file has multiple packages and classes, it is difficult for me to debug the issues using this file. And I don't have the source Java code. Is there a way to transpile back this JavaScript file to Java?

**Comment by lgrignon** [comment]
The feature you are looking for is called [Source Maps](https://developer.mozilla.org/fr/docs/Outils/D%C3%A9bogueur/Comment/Utiliser_une_source_map)
A source map can tell which line in the JS file maps to which line in the Java file so you can debug it easily in a browser dev tools for instance.

JSweet supports source maps generation, you just have to tell the transpiler to generate it.
Example, if you are using the JSweet Maven Plugin, according to the [documentation](https://github.com/lgrignon/jsweet-maven-plugin/blob/master/README.md), you should pass the following option:
```xml
<sourceMap>true</sourceMap>
```

**Comment by renaudpawlak** [comment]
Agreed on the source maps, but @giridhar2015 said he did not have the source code available, which means no source maps anyway.

If you don't have the original source code, it is not possible to go back from JavaScript to Java. In theory, we could provide such a feature, but since that's a very uncommon use case, that would probably be out of scope of the current project. So, unless I am missing something, the final answer right now is that, of my knowledge, there is no way to do such things in a close future.
