### ISSUE TITLE
Translations of InputStream, StringBuffer have missing methods

### ISSUE THREAD

**Issue by chrismiddleton** [cincheo/jsweet#265]
When an InputStream object is translated, it becomes this type:

    { str: string; cursor: number; }

I get these errors:

    ERROR output:48 - property 'available' does not exist on type '{ str: string; cursor: number; }'
    ERROR output:48 - property 'mark' does not exist on type '{ str: string; cursor: number; }'

Likewise, for StringBuffer, I am getting these errors:

    ERROR output:48 - property 'length' does not exist on type '{ str: string; }'
    ERROR output:48 - property 'charAt' does not exist on type '{ str: string; }'
    ERROR output:48 - property 'delete' does not exist on type '{ str: string; }'

A related issue is that classes which extend InputStream get an error about not being able to extend the object:

    ERROR output:48 - type 'StringBufferInputStream' is not assignable to type '{ str: string; cursor: number; }'

**Comment by chrismiddleton** [comment]
My workaround for now is to use my own StringBuffer implementation and name it StringBuffer2. (I believe when I tried just putting StringBuffer in directly, it still translated to the shortened jsweet version, so I had to add the 2.)

**Comment by renaudpawlak** [comment]
I have added some more support for StringBuffer, including the method you asked.
Regarding the input streams, I am afraid that it will be too difficult to find the time to support all Java APIs, especially because the mark method is not that simple. So if you really want it, I can explain you how to write your own adapter if you want to give it a try. Also, FI, J4TS version 0.5.0-SNAPSHOT is now compatible again with JSweet 2. However, J4TS also has limitations and I think it does not support input streams at all.

**Comment by renaudpawlak** [comment]
See https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#programmatic-tuning-with-adapters to see how to add new support Java APIs.
