### ISSUE TITLE
Tutorial/Guidelines for building JS APIs with jsweet

### ISSUE THREAD

**Issue by dharezlak** [cincheo/jsweet#268]
Is it possible to build a JS lib with jsweet which would expose an API based on a Java class/interface? In other words is it possible to use the generated code from the point of view of a JavaScript environment? If so are there any tutorials, examples or recommendations for doing that?

**Comment by renaudpawlak** [comment]
Sure. JSweet-generated APIs/code can be used from JavaScript as is (and even from TypeScript). To use from TypeScript, use the ``declarations`` option, that will generate the corresponding d.ts.

Functions taking primitive types and regular objects can be called as is. For Java int, float, double, ..., just pass a plain JavaScript number.

For Java collections/maps, it depends if you are compiling with JSweet 1.2.1 or JSweet 2.0.0-SNAPSHOT. With JSweet 1.2.1, you will need to use J4TS, but with JSweet 2.0.0-SNAPSHOT, you don't have to use it. So, two cases:

- **With J4TS (not recommended anymore).** You need to have the J4TS runtime available and instantiate a ``java.util.*`` implementation in your JavaScript program (for instance just write ``new java.util.ArrayList()``). For a map, write for instance ``new java.util.HashMap()`` in your JavaScript program and pass it to your JSweet-generated API.
- **Without J4TS (this is the best way but you have to use v2.0.0-SHAPSHOT).** All Java collections will be mapped to JavaScript arrays. So, just pass a plain JavaScript array for any collection! For passing Java maps from JavaScript programs, it depends if your map uses strings for keys or not. If your map is using string keys (for example: ``Map<String, Long>``) you just need to pass a JavaScript object with the right key-value pairs (properties) in it. For example, just pass ``{ "myKey1" : 1, "myKey2" : 2, , "myKey3" : 3}`` for a ``Map<String, Long>`` with 3 entries. If your map is taking any other type of keys, then you need to pass a JavaScript array containing key-value entries (eventually, you will also be able to use ES6 JavaScript maps).

Note that there are also the cases of using ``CharSequence``, ``Iterator``, which require to construct specific JavaScript objects when not using J4TS (I can explain more if your want).

All this will be explained in the specs when releasing version 2. Using J4TS will not be recommended anymore because it makes your JavaScript programs less compatible with JSweet and conversely (any JavaScript program using your API would need to instantiate Java-emulated objects or create JS objects from Java-emulated ones: you can see that it is really bad if you want to expose your program to any kind of JavaScript programmer). 

With JSweet v2 you can just use plain JavaScript objects all the time, which is better for performance and interoperability. Of course, I can imagine that there are still some cases where some people would want to use J4TS but I hope it will be rare enough.

**Last but not least**, JSweet v2 supports the translation from Javadoc comments to JSDoc comments :). Not only you can publish your JSweet-generated API to any JavaScript programmer, but you can also generate sound and JS-compatible documentation for it.

**Comment by dharezlak** [comment]
Thank you for this elaborate answer. Have you done any comparison to GWT's new JsInterop? I also have a GWT app which I will be integrating with jsweet. Is it possible to share a common Java code base and pass POJOs between the two frameworks?

**Comment by renaudpawlak** [comment]
So far I don't have enough data and time to extensively compare JsInterop with JSweet. JSweet has been designed from scratch to interoperate with JavaScript. JsInterop is more like an extension to a non-interoperable Java emulation core. You can probably use JavaScript-only objects when using JsInterop annotations, but I believe that it will be less "native"/built-in as when using JSweet v2, which maps to JavaScript all Java objects by default. Plus JSweet v2 is an open transpiler, which means you can easily change the way it maps Java to JavaScript objects for your own needs/environment.

Sharing JSweet v2-compiled POJOs with GWT-compiled POJO is the same problem as sharing JavaScript objects with GWT. So, in theory, you should be able to use JsInterop to access JSweet-compiled POJOs....
