### ISSUE TITLE
Can you provide a end to end example on how to map existing .js library?

### ISSUE THREAD

**Issue by PhilippePerez** [cincheo/jsweet#273]
I took me 10 minutes to understand in GWT how to map javascript code and unfortunately after spending a few hours i am still not able to do that in Jsweet. 

It seems the GWT like mechanism where javascript code was directly embeddable is not supported.
It was very convenient to map libraries . can we have this supported in the future please?
I thought specifying native would be enough but here we have an Ambient annotation which seems a bit redundant with native?

I surely miss some infos but i can't find a end to end ,self contained ( no maven ) example.

For the time beeing it seems i have to use maven to bundle a library which is not our standard build tool.
Also i regret a language depends on a build tool . I would like it to be more self contained to have more confidence that if i choose it for a long term project , i would be stuc in case the build tool becomes unsupported in the future.

Besides this i like the tool so i hope i will overcome this soon

Regards

**Comment by renaudpawlak** [comment]
Hum.... well, that's unfortunately true, there is much room for improvement with JSweet documentation and examples. Also, it is true that initially, JSweet was relying a lot on Maven (in candies) for bridging to external JS lib. It is not the case anymore. So, let me try to sum it up (I will write a more official document soon).

1. Please use JSweet v2 (2.0.0-SNAPSHOT). I can make a 2.0.0-RC1 if you want (because it is ready for it).
2. Do not use the ``@Ambient`` annotation. It is deprecated in JSweet v2 because it has limitations.
3. Use the "def" package convention, i.e. to bridge to an external lib, you just need to create a ``def.libname`` package in your project and put the Java classes that correspond to the JS lib you want to bridge. Of course, replace ``libname`` with the name of the library you want to bridge (this name has actually no real meaning except for you).

For example... let's say you want to bridge to a lib that declares a global ``f(param)`` function. All you need to do is to create a ``Globals`` class (contains global functions and variables) with a native function. (note that ``Globals`` is a JSweet convention)

```java
package def.libname;

public class Globals {
    public static native void f(String param);
}
```

That's all you need. "def" files acts a little bit like C "header" files. They are just here for compiling/declaring/typing the actual JS implementations. You can have as many "def" declarations as you want.

For more complete examples, please refer to https://github.com/jsweet-candies. You will find the declarations for most mainstream JS libs. Looking at the code will give you good hints on how to declare even complex APIs. For instance, here is the ``def.jquery`` package content: https://github.com/jsweet-candies/candy-jquery/tree/master/src/main/java/def/jquery.

These candies are deployed on our repo, so you can use Maven to add them to your projects, but if you don't want to use Maven, you can just cut and paste the parts you want in your project's code and JSweet will take care of the rest for you.

I hope this will make it clear. Please don't hesitate to tell me if something is not clear and I will do my best to explain better.

Thanks!

**Comment by PhilippePerez** [comment]
Thanks for your promt feedback ,i will see later on if i cn overcome my issues with this.

By the way i noticed 2 J4TS directories , you might want to delete one of them to avoid confusion
regarding where to find the latest version

http://repository.jsweet.org/artifactory/list/libs-release-local/org/jsweet/candies/j4ts/
http://repository.jsweet.org/artifactory/list/libs-release-local/org/jsweet/j4ts/

Regards

**Comment by renaudpawlak** [comment]
Thanks @PhilippePerez. Note that JSweet will generate a bundle (if you use the ``bundle`` option) that "only" contain the compiled code, but not external JS libs nor candies. In most candies, the JS code is available using the WebJar conventions and JSweet automatically extract it (see the ``candiesJsOut`` option). Then you need to include that JavaScript in your bundle manually or just include or require it in your Web page.

Although I understand it is convenient, I don't believe that trying to create a big bundle that contains all the dependencies is the best approach. The point is that there are good tools out there to help you manage your JS  dependencies. Typically, if you are developing a standard web application, you could use "bower" to manage/download your JS dependencies. If you don't like this way, you can also use WebJars through Maven. For node applications, you can use "npm". JSweet offers an alternate way because it extracts the JS if any from the candies if the JS is packaged (note that this behaviour is JSweet and has nothing to do we Maven).

About J4TS in the repo, it is probably a mistake. We will try to fix all this when releasing JSweet v2.

Thanks!

**Comment by renaudpawlak** [comment]
FYI I have deleted the http://repository.jsweet.org/artifactory/list/libs-release-local/org/jsweet/j4ts/ directory.
