### ISSUE TITLE
Overload Error (was Polymorphism Error)

### ISSUE THREAD

**Issue by PhilippePerez** [cincheo/jsweet#282]
Hi Renaud

While continuing to explore JSweet i can across an internal error which basically seems to mean ( if i believe the generated code ) that no matching method could be found while the java side is ok
See attached screenshot.

Incidentally , i worry the generated code that deals whith polymorphism gets inefficient when a lot of classes are in stake and such method get called in a loop. If you are interested i might have some optimisation suggestion. No sure if i have time to improve that myself . 

Transpiler version : jsweet-transpiler-1.2.1.jar
Not sure the 'always true' annotation i wrote in the image is correct because of the '===' operator ?

![polymorphism](https://cloud.githubusercontent.com/assets/25633027/26525110/7ec3d938-437f-11e7-968f-6db74636be6b.jpg)

**Comment by renaudpawlak** [comment]
To be more specific, it is an overload error (two methods having the same name but different signatures). Method overloading is not supported in JavaScript, so it needs to be emulated by JSweet. That's why the generated code adds code to check the parameter types at runtime and select the right overload.

Overloads have some limitations in JSweet, but globally they have been greatly improved in JSweet v2. Many bug fixes of course, but also they were optimized to directly call the right overload when possible and avoid the runtime checks. So, the performance issue you are fearing is fixed in v2. I am pretty sure that if you try to transpile your code with 2.0.0-SNAPSHOT, you will get much better output :) I am afraid I won't have time to fix your bug in previous releases of JSweet.

Thanks for your feedback.
