### ISSUE TITLE
Mixing native and non native code

### ISSUE THREAD

**Issue by PhilippePerez** [cincheo/jsweet#283]
Its about the possibility to mix native and non native methods but also the current behavior
is inconsistent ( from a Java programmer prospective) since the non args constructor is accepted, unlike
other methods with same signature.

![non native method](https://cloud.githubusercontent.com/assets/25633027/26525411/6da1d296-4388-11e7-97f4-9090bfe6e97d.jpg)

![non native method2](https://cloud.githubusercontent.com/assets/25633027/26525412/74d352ce-4388-11e7-8bbd-baec5816b0a9.jpg)

**Comment by renaudpawlak** [comment]
Right... Ambients follow a JSweet-specific convention that people have to understand outside of Java. Ambients (and definitions belonging to ``def.*`` packages) are close to TypeScript declarations. They cannot declare any implementation. That's why you have to declare methods as native. Also, you cannot initialize any field in an ambient context. Unfortunately, in Java, constructors cannot be native (or abstract). So in order to define constructor declarations, JSweet allows constructors with empty bodies (and only empty bodies). You can try to implement a body in your constructor and  JSweet will raise a transpilation error. Of course, it is not as consistent as I wish it would be, but I don't think there is a better solution in Java...

Note that ambients (definitions) should not generate any JavaScript code (but they should generate TypeScript declarations). If they generate JavaScript code, then it's a bug, but anyway the ``@Ambient`` annotation is deprecated in JSweet v2 and with JSweet v2, the only way to bridge external JS library will be to declare in ``def.*`` packages.

I hope it helps. Tell me if it remains unclear. I would be interested in some feedback for JSweet v2 around the same issues ;)
