### ISSUE TITLE
Optimizing dependency bundle.js

### ISSUE THREAD

**Issue by WhiteTrashLord** [cincheo/jsweet#284]
Do you plan to optimize the code  which is needed to run the Javascript code?
In my my case I would like to have no dependency of a second bundle.js at all.
I think I will only use very simple code which doesn't use any existing Java classes.
But maybe it's the best for me to use Typescript directly instead of coding in Java.

**Comment by WhiteTrashLord** [comment]
Oh it seems that it will be better in V2 :)

Can V2 work without any additional Javascript file ( like j4ts.js or bundle.js )?

**Comment by renaudpawlak** [comment]
That's right, with v2, you don't need any runtime (such as J4TS). So you can use most Java core APIs and JS APIs within the same program and the generated code will not require any external js file (unless you are using an external non-core lib of course).

Even better, the generated code is JavaScript-compatible when possible. For instance, all collections are generated as JavaScript arrays, maps are generated as JS objects and so on... this makes the generated JS compatible with regular JavaScript libraries even when using Java APIs. Also, Javadoc comments are generated as JSDoc :)

Last but not least, if you don't like the way JSweet generates the JavaScript code, it is easy to write an extension to tune it.

You can already use v2.0.0-SNAPSHOT. It is almost ready for production but not released yet mainly because we need to have the time to write the docs and update the web site.

**Comment by WhiteTrashLord** [comment]
I would like to test V2. Do you know if it already works with the Eclipse Plugin?

**Comment by renaudpawlak** [comment]
Umm... no it is not available yet :(
But if you want on-the-fly compilation in your favorite IDE, you can run the command:

```
mvn jsweet:watch
``` 

Run it on your project and it will start a job that will automatically transpile your project when your Java code changes (you need to have a ``pom.xml`` and Maven installed of course).

**Comment by renaudpawlak** [comment]
Eclipse plugin will be upgraded when v2 will be out.
