### ISSUE TITLE
Bitwise operations are transpiled to logical operations

### ISSUE THREAD

**Issue by CodingPfeffer** [cincheo/jsweet#302]
I found a [bug ](https://github.com/j4ts/j4ts/issues/17) in the j4ts candies, which results in a broken AbstractSet.addAll method.

This happens because the jsweet transpiler changes a bitwise operation to a logical one. This results in "early return strategy" being applied to that operation, which is not done for bitwise operations.

`bool1 | bool2`
is wrongly transpiled to
`bool1 || bool2`

**Comment by renaudpawlak** [comment]
Thanks for reporting. That's because of || and | operators meanings in TypeScript... | is only bitwise and can only apply to numbers, while || is logical and can only apply to boolean. As a consequence, TypeScript only allows short-circuit boolean operators... Right now I am not sure about how to deal with it.

At least for the case ``b |= expr`` we could generate ``b = expr || b`` instead of ``b = b || expr``. That would solve the j4ts bug because it would force expr to be evaluated (and ``b`` being a variable it does not matter if short-circuited or not...).
