### ISSUE TITLE
Feature request : support for minimalist Bean design pattern

### ISSUE THREAD

**Issue by Eclesia** [cincheo/jsweet#308]
Beans are common in java and many API work based on them.
Dynamic editors and events are the most comon cases.

To support a 'bean like' design it would require to implement a minimal set of reflection on methods

Here is what a minimal bean utility class would look like
```
public static Method getReadMethod(Class clazz, Chars name){
        final String name1 = "is"+name;
        final String name2 = "get"+name;
        for(Method m : clazz.getMethods()){
            if(m.getName().equals(name1) || m.getName().equals(name2)){
                return m;
            }
        }
        return null;
    }
    
    public static Method getWriteMethod(Class clazz, Chars name){
        final String name1 = "set"+name;
        for(Method m : clazz.getMethods()){
            if(m.getName().equals(name1)){
                return m;
            }
        }
        return null;
    }
```
And the invoke method.
```
m.invoke(obj, value);
```

So the full list of method used would be :
```
Class#getMethods
Method#getName
Method#invoke
```

What do you think ? could it be possible ?

**Comment by renaudpawlak** [comment]
Hey. This is done. I have stored methods in small objects containing the following properties:
- ``owner``: the owning class, i.e. the constructor of that class most of the time
- ``name``: the function name
- ``fn``: the actual function

So the ``getMethods`` function returns a list of that kind of objects. After that, it is easy to transpile ``m.invoke(o, args)`` to ``m.fn.apply(o, [args])``.

Of course there are a lot of limitations for reflection since much information is missing at runtime. For example you will not be able to inspect method parameters or return types. That will not be possible unless we decide to add some runtime type information. This could be one day a JSweet extension, but I believe it should not be provided by default because it would consume JavaScript memory for very marginal use cases. 

More importantly, there will be limitations with interfaces, and maybe with overloaded methods (have not tested yet). So far, I sticked to your very simple use case. We may extend it later if needed.
