### ISSUE TITLE
java varargs

### ISSUE THREAD

**Issue by isakovarseniy** [cincheo/jsweet#338]
Hi 

First class
```
package com.octo.sql.exp;

public class OrExp extends ExpSeq {
  OrExp(final Exp... clauses) {
    super(clauses);
  }

  @Override
  public Operator getOperator() {
    return Operator.OR;
  }
}

```
Second class

```
package com.octo.sql.exp;

import java.util.Arrays;
import java.util.List;


public abstract class ExpSeq extends Exp {
  protected final List<Exp> clauses;

  ExpSeq(final Exp... clauses) {
    super();
    this.clauses = Arrays.asList(clauses);
  }

}

```
Third class

```
package com.octo.sql.exp;

public abstract class Exp {
 
}

```
Error during transformation

argument of type 'Exp[]' is not assignable to parameter of type 'Exp'

Regards
Arseniy Isakov

**Comment by renaudpawlak** [comment]
Yes. Varargs have still limitations, especially with constructors :(
The root cause has to do with how TypeScript handles varargs... but the way we overcome that problem it probably not right. It might require some deep changes on how varargs are handled, but I am not sure yet... I'll think about it.

**Comment by renaudpawlak** [comment]
After investigation, it seems easier than expected... your issue #337 gave me some leads (using the ... typescript syntax). Latest snapshot should work on this case now. Thanks.
