### ISSUE TITLE
@Replace annotation

### ISSUE THREAD

**Issue by isakovarseniy** [cincheo/jsweet#339]
Hi

Currently @Replace is not working with class contractor.
Is it possible to add this functionality to replace constructor body

Thanks
Arseniy Isakov

**Comment by renaudpawlak** [comment]
Ok, you'll find it in the latest snapshots jsweet-transpiler and jsweet-core. It was easy to activate it because it was already possible (the annotation's target was not defined properly). Note that ``@Replace`` will probably have limitations when using overloading and in constructors when using the ``{{ body }}`` marker... I have not tested all configurations...
