### ISSUE TITLE
Comparison of Enums with == operator fails

### ISSUE THREAD

**Issue by negora** [cincheo/jsweet#349]
Hello:

I've a simple `Enum` like this:

```java
public enum MyEnum {
  A,
  B,
  C;
}
```

And I'm doing this comparison:

```java
MyEnum e = MyEnum.A;
boolean result = (e == MyEnum.B);
```

But I'm getting' this error from `tsc`:

> error TS2365: Operator '===' cannot be applied to types 'MyEnum.A' and 'MyEnum.B'.

Curiously, if I compare `e` against the same value, so that the comparison results `true`, it works fine:

```java
MyEnum e = MyEnum.A;
boolean result = (e == MyEnum.A); // <- B has been replaced with A
```

Thank you.

**Comment by renaudpawlak** [comment]
Yes. That's "normal". TypeScript 2 has a much more powerful type inference engine than TypeScript 1 or Java. With TypeScript 2, each enum constant has its own type (also, I think that true, false, null and other values have their own types). It means that ``e == MyEnum.B`` will raise an error if the compiler can infer that ``e`` is of type ``MyEnum.A``, which is the case here because ``e`` is assigned to ``MyEnum.A`` right before. On the other hand if you wrap the comparison in a function for instance, then it is OK because the compiler will not infer the type of ``e`` precisely...

```java
public boolean cmp(MyEnum e) {
    // ok because e cannot be inferred to an enum constant type
    boolean result = (e == MyEnum.B);
}
...
boolean result = cmp(MyEnum.A);
```

That's tricky... Personally, I don't like it too much because it avoids writing simple test statements such as ``MyEnum.A != MyEnum.B`` (this will raise a compilation error). It is pushing type safety a little be too far for my taste... However, in real-life programs, you never write that sort of statements, and you can always erase the typing to force it to compile.

For instance, for your case I think you should be able to write:

```java
import static jsweet.util.Lang.any;

MyEnum e = any(MyEnum.A);
boolean result = (e == MyEnum.B); 
```

or:

```java
import static jsweet.util.Lang.any;

MyEnum e = MyEnum.A;
boolean result = (any(e) == MyEnum.B); 
```

A question that can be asked is to decide wether JSweet should automatically erase typing in that cases to loose typing and stick to the Java type inference. However, I believe that even if surprising, it could be a good thing to keep TypeScript do its typing job as much as possible...

Don't hesitate to give you opinion about this.

**Comment by negora** [comment]
Oh, I had no idea that it was a feature of TypeScript 2. Thank you for the clarification, as always ;) .

I also find this type of checks very invasive. But, on the other hand, I like that the compiler is so clever to detect this type of errors. As long as it's easy to circumvent these checks when we need it (by your examples, it looks like that), I'm OK with them. I'd leave them enabled.

I also have a question or bug report with regard to compare `enums` with the `equals()` method. But I better open another ticket instead, not to mess this one up.

Thank you a lot!

**Comment by renaudpawlak** [comment]
Ok. We agree then. Closing this one.
