### ISSUE TITLE
Arrays::asList 

### ISSUE THREAD

**Issue by enricostara** [cincheo/jsweet#350]
Hi,

I tried the following:

```  
@Replace("return new java.util.Arrays.asList(this.tileMap.values().toArray().filter(tile => tile.elevation === elevation));")
public Collection<Tile> getTilesByElevation(int elevation) {
    return tileMap.values().stream().filter(tile -> tile.elevation == elevation).collect(Collectors.toList());
}
```
but the returned List has only one element: the whole filtered array.. therefore, if I start an iteration, I'll get a single Tile[] object.

Could you please help me to understand if I found a bug in Arrays::asList method or If I'm doing something wrong?

Thanks,
Enrico

**Comment by renaudpawlak** [comment]
I think it's because ``asList`` takes a varargs, so you cannot pass an array as is. If you are using JSweet 2 (which uses TypeScript 2), you can try:

```java 
@Replace("let a = this.tileMap.values().toArray().filter(tile => tile.elevation === elevation); return new java.util.Arrays.asList(...a);")
```

For more info, check the docs on TypeScript + spread operator.
If you are using JSweet 1, you need to use ``apply``, which should have the same effect.

Just for my own understanding, your are obviously still using the J4TS runtime. It did not work for you without it? If you had errors, that would be great if you find the time to report. If you use it on purpose, I would be curious to know your use case.

**Comment by enricostara** [comment]
Great hint!
therefore I can just use the following:
```
    @Replace("return java.util.Arrays.asList<Tile>(...this.tileMap.values().toArray().filter(tile => tile.elevation === elevation));")

```

Yes, I'm using J4TS.. Could I do without it? Please, consider that I'm writing plain java code using Map, List,  Collection and primitive wrappers (where needed). Can I use them without J4TS?

**Comment by enricostara** [comment]
I just try to remove J4TS from dependencies and seems that only the @Replace does not work (of course).

Now, in order to remove completely J4TS, I guess that I have to rewrite @Replace accordingly (returning Array instead of java.util.List ..)

**Comment by renaudpawlak** [comment]
That's right. You need a pure JavaScript implementation. If your map has string key, that should be something like (not tested):

```typescript
return Object.keys(this.tileMap).map(key => obj[key]).filter(tile => this.elevation === elevation);
```

Note that you could also seize the opportunity to write an adapter to support the Java stream API. See https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#extending-the-transpiler. You would not need the ``@Replace`` annotation anymore then :D
