### ISSUE TITLE
Issue with *

### ISSUE THREAD

**Issue by isakovarseniy** [cincheo/jsweet#352]
Hi

I have following class

```
package t;

import static org.junit.Assert.assertEquals;

public class A1 {
	public void test1(){
		
		assertEquals(1,1);
		
	}
}
```
Using customization I got this
```
/* Generated from Java with JSweet 2.0.0-SNAPSHOT - http://www.jsweet.org */
import {assert, expect} from "~chai/lib/Chai";
let assertEquals: any = Assert.assertEquals;
export class A1 {
    public test1() {
        expect(1).to.equals(1);
    }
}
A1["__class"] = "t.A1";



var __Function = Function;

```

Transpiler automatically insert
let assertEquals: any = Assert.assertEquals;

To avoid this situation I have modify my java class
```
package t;

import static org.junit.Assert.*;

public class A1 {
	public void test1(){
		assertEquals(1,1);
	}

}
```
in this case transpiler   generate right code but I am getting exception
ERROR output:55 - imports cannot use * wildcards when using modules: please import a specific element at /Users/arseniy/MyPrj/git/tura.4.3.0/platform/java-sql-dsl/src/test/java/com/octo/sql/UpdateQueryTest.java

Error doesn't allowed complete build
Thanks
Arseniy Isakov

**Comment by renaudpawlak** [comment]
Umm. Do not use * wildcard for modules.
Instead, to erase an import, you are supposed to override the ``needsImport`` method in your adapter.

```java
					@Override
					public String needsImport(ImportElement importElement, String qualifiedName) {
						if(qualifiedName.startsWith(...)) {
							// remove the import
							return null;
						} else {
							return super.needsImport(importElement, qualifiedName);
						}
					}
```

This might fix your issue, however, I think that the root cause of your problem may be that this line here ``let assertEquals: any = Assert.assertEquals;`` is actually not needed anymore and should probably not be generated by JSweet. I am investigating this. I'll come back to you ASAP.

**Comment by renaudpawlak** [comment]
Ok. I have worked on imports and modules... apparently, your case should now be working as is because the ``let assertEquals: any = Assert.assertEquals;`` is not generated anymore. Just to be sure:

- don't use * imports
- no need to override the ``needsImport`` method in your adapter

Tell me if it works... Thanks!

**Comment by isakovarseniy** [comment]
Yes it is working
Thank you
Arseniy Isakov
