### ISSUE TITLE
Online TypeScript to Java API translator issue

### ISSUE THREAD

**Issue by enricostara** [cincheo/jsweet#356]
Hi,

I spent a couple of hours trying to translate the last version of Babylon.js, but the online translator seems not able to give me a stable support.

I just need to have the last stable version of Babylon (3.0) in order to have also the new GUI module.
Is there a different way to have the v3.0 with GUI translated in one candy? what I can do to support?

Thanks and regards,
Enrico

**Comment by renaudpawlak** [comment]
I guess that the Babylon candy that is already in our [repo](http://www.jsweet.org/candies-releases/) is outdated? If you need to create that candy for the latest version (or create a candy for a new module), then you can use our candy generator tool.

Everything should be explained in https://github.com/cincheo/jsweet/tree/master/candy-generator. Once you get it to work on simple ``d.ts`` files, you need to feed it with latest Babylon.js ``d.ts``. The output will give you a head start for creating a candy. However, you will probably need to adapt the Java code (maybe resolve some compilation issues, add missing API, ...).

Before you have a candy published and working, you should simply put the Babylon API directly in a ``def.babylon`` package in your project so that you can try it, modify it, adjust it, fix it and whatsoever. Just copy-paste the *.java output of the candy generator in your project source.

I invited you in the https://github.com/orgs/jsweet-candies organization in case you manage to get a stable version that you would want to share in JSweet candies repository. You can then create or clone a Babylon candy there and I can help making it better if needed.

Finally, you may want to contact @ssatguru, who created a [BabylonJS project](https://github.com/ssatguru/Vishva) with JSweet 1 (. Although JSweet 2 has been largely improved since then (creating and modifying candies is much simpler now), he may give you some good insights/feedback on working with JSweet and BabylonJS.

**Comment by enricostara** [comment]
Yes, that's right. The current version published in repo is outdated and this is what I'm currently using.

Thanks for your invitation! I'll try to use the candy generator to port the latest Babylon version and if I'll get something stable I'll try to share it in JSweet candies repository.

Thanks,
Enrico

**Comment by enricostara** [comment]
Done. 

I followed your info and solved some little compilation issues, you should find now the new candy.
I tested with my application and it's working fine. Btw, let me know if something is not compliant or not as expected.
Finally, I was not able to mvn deploy for missing authorisation. 

I'll try soon to add a second candy with also the babylonjs-gui submodule.

**Comment by renaudpawlak** [comment]
Great! Thanks!

**Comment by enricostara** [comment]
Welcome :)
Is it possible also to deploy in jsweet-candy maven repo?

**Comment by renaudpawlak** [comment]
Yes. I'll do it ASAP (and also the JavaDoc). I have an emergency to deal with first. Ping me if I forget :)

**Comment by enricostara** [comment]
Hi, 
I just added a CI tool to manage my app lifecycle and I can see that the external tool is not able to download the lib from mvn. Could you please deploy the 3.0.7 version? 
many many thanks in advance :)

**Comment by enricostara** [comment]
Hi Renaud,

only a gentle reminder if you can deploy o give me the auth to deploy the mvn artifact ;)

**Comment by renaudpawlak** [comment]
Oops. Sorry, tooooo busy :D
I don't know from the top of my head how to to give scoped permission to the artifactory repo. So I deployed it myself. Tell me if it is good for you.
Thanks!

**Comment by enricostara** [comment]
Hi, thanks for the support!

Still we have an issue, the deployed jar seems to be not completed!

After the download I found the following fundamental part is missing:

`/META-INF/resources/typings/babylonjs/3.0.7/bundle.d.ts`

Could you please check if during `mvn install` phase before deploy something goes wrong on your side?

Many thanks!
Best
Enrico

**Comment by enricostara** [comment]
Sorry Renaud, it was my fault!
I just figure out that I leaved the bundle.d.ts file git-ignored and therefore it was missing in repository (the file is provided and no more generated..).
Please, checkout the last version and try to run again the mvn deploy.

Many many thanks again!
Enrico

**Comment by enricostara** [comment]
Hi Renaud,

only a gentle reminder if you can deploy again ;)

**Comment by enricostara** [comment]
Hi, any chance to have the package deployed? Tell me if I can do something to help!
Could I manage, for example,  to deploy in another public mvn repo?

**Comment by lgrignon** [comment]
I will do this right now

**Comment by lgrignon** [comment]
Could you please try again?

**Comment by enricostara** [comment]
Hi,

I tried to download again and it still is the corrupted version :( 
Since I didn't change the version (always 3.0.7) could it be possible that something is caching the previous artifact in the server?

I also tried to clone https://github.com/jsweet-candies/candy-babylonjs.git from scratch locally, and after running mvn install the artifact is as expected, therefore I'm definitively sure that all it's ok!

Could you please verify also if before your mvn deploy the file src/main/resources/META-INF/resources/typings/babylonjs/3.0.7-20171101/bundle.d.ts was there?

Many thanks for your kind support!

E

**Comment by lgrignon** [comment]
Yes. File was cached in your local repo. Please try to remove .m2/repository to confirm.
Thanks

**Comment by enricostara** [comment]
Ok, just realised that the version was updated by Renaud: 3.0.7 > 3.0.7-20171101

My project was still using, of course, the old one.. Just updated and I confirm you that all is fine!

Many thanks :)

E

**Comment by enricostara** [comment]
Sure, I pruned from the beginning my local repo ;)

**Comment by renaudpawlak** [comment]
Hey. I thought you would have received the notification of my commit. Please note that all candies *must* be post fixed by the date like I did. You should *never* use plain release numbers like you did :) that's because the release number is the release of the bridged API and you may have to release several versions of the candy for the same  API version. I don't know if it is cLear :)

**Comment by lgrignon** [comment]
@enricostara haha ok sorry, that was just in case ;) 
Happy that it's fixed
