### ISSUE TITLE
Erasing class based on dynamic parameters

### ISSUE THREAD

**Issue by isakovarseniy** [cincheo/jsweet#357]
Hi 

I have converted my library to typescript including test classes. 
Now I'd like to generate 2 separate bundles. one is my main logic , another with tests 
I have created following config: 
```
			<plugin>
				<groupId>org.jsweet</groupId>
				<artifactId>jsweet-maven-plugin</artifactId>
				<version>2.0.0-SNAPSHOT</version>
				<executions>
					<execution>
						<id>generate-js</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>jsweet</goal>
						</goals>
						<configuration>
							<bundle>true</bundle>
							<module>none</module>
							<outDir>target/ts/source</outDir>
							<tsOut>target/ts/source</tsOut>
							<dtsOut>target/ts</dtsOut>
							<declaration>true</declaration>
							<sourceMap>true</sourceMap>
							<targetVersion>ES5</targetVersion>
							<verbose>true</verbose>
							<includes>
								<include>**/*.java</include>
							</includes>
							<excludes>
								<exclude>**/test/**</exclude>
							</excludes>

						</configuration>
					</execution>

					<execution>
						<id>generate-test</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>jsweet</goal>
						</goals>
						<configuration>
							<bundle>true</bundle>
							<module>none</module>
							<outDir>target/ts/test</outDir>
							<declaration>true</declaration>
							<sourceMap>true</sourceMap>
							<targetVersion>ES5</targetVersion>
							<verbose>true</verbose>
							<includes>
								<include>**/*.java</include>
							</includes>
							<excludes>
								<exclude>**/main/**</exclude>
							</excludes>
							
						</configuration>
					</execution>
				</executions>
			</plugin>

```
Second execution gives me compilation  error because I have excluded files from src/main/java.
So instead of  "excluded"  I need dynamically erase classes from src/main/java. Can you please give me some advice how to do this?

Thanks
Arseniy Isakov

**Comment by renaudpawlak** [comment]
I am unsure of what you are really trying to do here.
If your tests are using your main classes (which is logical), then you need to generate the JavaScript code for the main classes when compiling (and running) your tests, right? So IMO, you should remove the exclude from you test configuration. But maybe I miss something...

**Comment by renaudpawlak** [comment]
Umm. I missed that you want to generate 2 separate bundles... I am unsure that it is required to have 2 separate bundles here. To me, the important is that the main bundle is independent (and does not contain the test classes). Then, the test bundle can include all the main classes, I don't see the problem with that approach. So I would stick to my initial advice.

However, if for some reason I don't understand, you really need to have separate bundles (with the test bundle using the main bundle externally), then I think that dynamically erasing the main classes is not the solution because then the TypeScript to JavaScript compilation would fail (it would require non-existing TypeScript classes). So it would get more complicated... You'll probably need to generate some sort of candy for your main bundle, which would include the Java main classes and the TypeScript definitions so that JSweet can compile the tests against that candy. I'd say it's doable, but I have never tried such as way. Tell me if you try to go for it and need some help.
