### ISSUE TITLE
jsweet-core (6-20170726): many important methods and fields are missing

### ISSUE THREAD

**Issue by Davren88** [cincheo/jsweet#360]
Hey guys,
I tried to update my jsweet project from 1.2.0 to 2.0.0 (I also used jsweet.core with version 1.2.0-SNAPSHOT which worked really well).
Now I figured out, that the latest version jsweet-core (6-20170726) misses many important methods.. Here is a small list (was available in 1.2.0 SNAPSHOT):

- Window.java:
native public Object $get(String name); (there is only native public Window $get(double index); availble)
doesn't have the method removeEventListener anymore?

- Object.java:
it references 

@see jsweet.util.Lang#$get(String)
@see jsweet.util.Lang#$set(String,java.lang.Object)
@see jsweet.util.Lang#$delete(String)
native public void $set(String key, java.lang.Object value);

but there is no such a method like sweet.util.Lang#$set(String,java.lang.Object) in jsweet.Lang. 

- Element.java:
innerHTML as field doesn't exist anymore?

these are just some cases I found out.. I guess, there were plenty more. It is also possible, to use jsweet-core 1.2.0 SNAPSHOT for jsweet 2.0.0, too?

**Comment by renaudpawlak** [comment]
First things first: don't panic ;)

Migrating from JSweet 1.x to 2 is very easy. The first thing to do is to use ``def.js`` in place of ``jsweet.lang`` for JavaScript core APIs and ``def.dom``  in place of ``jsweet.dom``. Then, you need to use ``jsweet.util.Lang`` instead of ``jsweet.util.Globals``. Since this API has changed a little, you may have to change a few things in your code.

According to your feedback, you must have a configuration issue somewhere, or you are misusing something... For instance, I have just checked ``Element.innerHTML``. It is (of course) still there. Make sure you are using ``def.dom.Element`` (and not another ``Element`` of some other lib).

If you have a doubt, check out the Javadoc: http://www.jsweet.org/core-api-javadoc/

Also, ``def.dom.Window.$get(String)`` still exists because Window extends ``def.js.Object``, which defines it. And I have just tried ``removeEventListener``... it is ok too.

Now... you are right for one thing though, the JavaDoc for ``Object.$set`` still references ``jsweet.util.Lang#$get/set/delete`` methods, which has been removed. That's a mistake in the doc. I will fix it right away. On the other hand, ``jsweet.util.Lang#$get/set/delete`` methods have been indeed removed because the API ``def.js.Object.$get/set/delete`` has been improved (with generics) and it is redundant to have static helpers. So... all use of static helpers in JSweet 1.x such as:

```java
import static jsweet.util.Lang.$get;
[...]
$get(o, "aFieldName");
```

must be rewritten to:

```java
import static jsweet.util.Lang.object;
[...]
object(o).$get("aFieldName");
```

Note that you don't need to use the ``object`` helper if ``o`` is already a ``def.js.Object``.  Another way to do it is simply a cast:

```java
((def.js.Object)o).$get("aFieldName");
```

So, to conclude, you probably first have a configuration "mystery" to solve, but once it is solved the only thing you will have to change most probably is converting the static calls to ``$get/set/delete`` to non-static ones on ``def.js.Object``.

Last but not least... in theory, JSweet 2 is backward compatible, which means you can use the old v1 API with JSweet v2. You could even mix old and new APIs. However I strongly recommend NOT to try it because it will make your program extremely messy (I have tried it). Please, try to fix and move to the new API. Don't hesitate to report more issues if you see that something is actually missing once you have solved your "mystery".

Thanks!

**Comment by Davren88** [comment]
Thanks mate :)
I just figured out the problem... I used jsweet-core 6-20170726 (you can check it out.. for example, Window  doesn't extend from anything there ;) ) insted of 5-20170726 - which exactly contains the stuff I need.

**Comment by renaudpawlak** [comment]
I am reopening this issue to remember that version 6 needs to be fixed.

**Comment by lgrignon** [comment]
ES6 core candy now works:
https://github.com/cincheo/jsweet-quickstart/

If some methods are missing, it is possible to contribute by a PR to https://github.com/cincheo/jsweet/tree/master/core-lib/es6

That being said, I pushed the Window enhancement you suggested to extend def.js.Object
Element.innerHTML does not exist anymore because it is available on HTMLElement, which is - at the end - more relevant.

Please feel free to fix more stuff in the core candy if you see something;
