### ISSUE TITLE
JSweet 2.0.0 candies availability

### ISSUE THREAD

**Issue by supertote** [cincheo/jsweet#372]
Hi,

I have been using jsweet for a couple months and loving it.
Now I would like to migrate to jsweet 2.0 but it seems that in the repository not all candies have been updated. Specifically I am using three candies:
- jquery : updated for jsweet 2.0.0 as 1.10.0-20170726 - OK
- jqueryui: updated for jsweet 2.0.0 as 1.10.0-20170726 - OK
- dojox.jq: I can't find an updated version.

Am I missing something or what is the plan for updating candies?

**Comment by lgrignon** [comment]
Hi @supertote 
With JSweet 2.0.0, some well known and popular candies were deployed (jquery, angular, ...) but not all are automatically deployed.
Candies are now fully open source so there is a GitHub [organization
](https://github.com/jsweet-candies) which holds all the official candies repositories / projects.
They were all set up using the candy-generator: https://github.com/cincheo/jsweet/tree/master/candy-generator
 (which is based on libraries' TypeScript definitions) and pushed by contributors.

Since dojox.jq was available before, it should be easy to regenerate and push the JSweet v2 candy for this library.

You can generate the candy on your own and play around with it, and, when you are ready and if you feel this way, I can grant you on the jsweet-candies organization so you could share the candy with the community.

**Comment by supertote** [comment]
Thanks for the clarification.
I will play around with generating my own candy but since I will be using very little from dojox, I might not be able to be in a position to publish someting really validated. We will see.
