### ISSUE TITLE
Error: cannot invoke abstract overloaded method

### ISSUE THREAD

**Issue by alievrenkut** [cincheo/jsweet#374]
First thanks for fixing J4TS issue. 
Now I can compile my project but I guess there is a problem with transpiler. For example if you write below code
`new BufferedReader(new StringReader("1\n2"),512).readLine()`
will throw 
> Error: cannot invoke abstract overloaded method

Stacktrace:
> Reader.read$char_A$int$int (bundle.js:420)
> BufferedReader.fill (bundle.js:7500)
> BufferedReader.readLine$boolean (bundle.js:7597)
> BufferedReader.readLine$ (bundle.js:7655)
> BufferedReader.readLine (bundle.js:7649)

BufferedReader.fill method wrongly calls method of Reader instead of BufferedReader.

Also there is a similar overloading problem which:

ArrayHelper.insertInto(this.array, 0, c.toArray()) method call inside constructor ArrayList(Collection) executes method `ArrayHelper.insertInto(Object, index, Object)`
instead of `ArrayHelper.insertInto(Object,index,Object[])`
which creates an ArrayList containing array inside another array.
This issue is reported in https://github.com/j4ts/j4ts/issues/20 and https://github.com/j4ts/j4ts/issues/18

**Comment by renaudpawlak** [comment]
Sorry for late answer but I have very little time. Looks like a complicated but quite annoying issue. I'll try to work on it asap, but any help would be appreciated (such as full failing exemples that can be used as tests). Thanks anyways for reporting this.

**Comment by schaumb** [comment]
From now if the pull requests are accepted, the j4ts repo contains the StringReader class, and no fails with ArrayHelper.insertInto too:
https://github.com/j4ts/j4ts/pull/37
https://github.com/j4ts/j4ts/pull/39
The above example code compiles and works as expected.


Without j4ts it can not be call ".readLine()" function, because it is not a core functionality of javascript strings, and BufferedReader wrapper class.

**Comment by schaumb** [comment]
yes :)
