### ISSUE TITLE
The def.js.Array.join method is confusing

### ISSUE THREAD

**Issue by travelbasys** [cincheo/jsweet#378]
Hello.
Please look at this code:
```
		// Use regular JavaScript API.
		def.js.Array<String> myArray = new def.js.Array<>();
		myArray.push("Hello", "world");
		
		String separator = " - ";
		def.js.String message = myArray.join(separator);
```
Here _String_ means _java.lang.String_.

So, the _join(String)_ method requires an argument of type _java.lang.String_, but returns a value of type _def.js.String_. Isn't that strange? 
After all, _"Hello", "world",_ and _separator_ are all _java.lang.String_ and that is even the generic type of our array. That looks confusing.

Maybe we should have the following overloaded methods:
_public java.lang.String join(java.lang.String)_
_public def.js.String join(def.js.String)_

The existing one
_public def.js.String join(java.lang.String)_
is actually no good for anything. Or is it?

Just wondering...

**Comment by lgrignon** [comment]
Yes you are perfectly right. There many small enhancements which would make perfect sense in the def.js.* API. The one you proposed is nice. 
Could you make a PR for https://github.com/cincheo/jsweet/tree/master/core-lib/es5/src/main/java/def/js
So we could redeploy it in the near future ? 
Thanks

**Comment by renaudpawlak** [comment]
Yes, that's a possible improvement of the API (actually I think I did apply it in some places).
Let me just mention that the ``string`` utility method allows you to cast back and forth from ``java.lang.String`` to ``def.js.String``. So... you can import static the ``string`` method and use it.

```java
import static jsweet.util.Lang.string;
[...]

		// Use regular JavaScript API.
		def.js.Array<String> myArray = new def.js.Array<>();
		myArray.push("Hello", "world");
		
		String separator = " - ";
		String message = string(myArray.join(separator));
```

That's not perfect, but it helps ;)
Actually there is no perfect solution when working with strings and JSweet. Sorry, that's a Java constraint :( You will hit similar limitations with arrays (but that's less an issue...).... But besides that, I think it's OK ;)

**Comment by travelbasys** [comment]
Yes, I found the _string_ function, too.
Another way which should work is _myArray.join (separator).toString()_ since _toString ()_ always returns a _java.lang.String_.

**Comment by travelbasys** [comment]
Hi.
I’m not familiar with Pull Requests.
But it looks like my proposed change was already in master 5 months ago and was changed by Renaud Pawlak to the current version.
See: „various improvements preparing v2“.

Cheers.
Hubert

**Comment by renaudpawlak** [comment]
I am not sure which change you are referring to.
Basically, in the current API, Array.join can take a string of any kind (``java.lang`` and ``def.js``) but always returns a ``def.js`` string. That's to allow fluent interface on JS strings I guess, but that not perfect...  If I did it this way, probably I had a case where it looked better, but it does not mean it will always look good.

Yes you can use the ``toString`` method. It will work for most modern browsers, but for sake of efficiency and backward compatibility with older browser, I advise to use the ``string`` cast method.

In any case, I don't think that there is a real issue here (that's more of a discussion about the best way to present the JS API for strings). So I am closing the issue.

**Comment by travelbasys** [comment]
Hi.
You ask what change I am referring to.

I am referring to the following commit:
11c8062 on 03.05.2017 at 12:41:51 MESZ - various improvements preparing v2.

Here you removed the following lines from def.js.Array:

    /**
      * Adds all the elements of an array separated by the specified separator string.
      * @param separator A string used to separate one element of an array from the next in the resulting String. If omitted, the array elements are separated with a comma.
      */
    native public java.lang.String join(java.lang.String separator);

    /**
      * Adds all the elements of an array separated by the specified separator string.
      * @param separator A string used to separate one element of an array from the next in the resulting String. If omitted, the array elements are separated with a comma.
      */
    native public java.lang.String join();

And the following lines were added (you have to read quite a few lines of the diff):

	/**
	 * Adds all the elements of an array separated by the specified separator
	 * string.
	 * 
	 * @param separator
	 *            A string used to separate one element of an array from the
	 *            next in the resulting String. If omitted, the array elements
	 *            are separated with a comma.
	 */
	native public String join(java.lang.String separator);

	/**
	 * Adds all the elements of an array separated by the specified separator
	 * string.
	 * 
	 * @param separator
	 *            A string used to separate one element of an array from the
	 *            next in the resulting String. If omitted, the array elements
	 *            are separated with a comma.
	 */
	native public String join(String separator);

So, you in fact replaced
	public java.lang.String join(java.lang.String)
	public java.lang.String join()

by
	public def.js.String join(java.lang.String)
	public def.js.String join(def.js.String)

I would not think that is a very good decision, because in this way you even loose the option of calling join() parameterless, which JavaScript allows.
But see below.

What I advocate for is to have these overloads:
	public java.lang.String join(java.lang.String)
	public def.js.String join(def.js.String)
and also a third one
	public def.js.String join()
or
	public java.lang.String join()
whichever you think is „better“ or more in line with similar cases.                     

Now for the parameterless signature, which is allowed by JavaScript, too.
I am somewhat confused here.
The compiler at present seems to accept public def.js.String join() without error message, but I am utterly ignorant where it takes its justification from.
Is there another overload defined in some other place that I did not see?
At least Eclipse reports no error. Hm.
Does some „macro“ treat the parameterless case as equal to an empty argument string? Maybe.
Note that in the old version there was an explicit parameterless overload.

I agree with you that this is not a „real issue“.
So you may or may not keep the item closed.
But doing things in a different way would remove just a tiny bit of mild irritation, yes?

By the way, the fluent interface idea, that you mention, probably goes more in favor of may proposition.
In any case, JavaScript itself does not seem to entertain such a notion in our context here, or does it?

Regards.
Hubert

**Comment by renaudpawlak** [comment]
Sorry but Github issue management is not very subtle. Closing it does not mean that we don't have to try to find a better solution :) If we find that there is a course of action to be taken we will clearly open it.

So, the thing is that I tried out many ways of doing things with strings, and as I said there is no perfect way of doing things. It turned out that returning ``def.js.String`` in ``def.js.String`` and ``def.js.Array`` simplified some expressions significantly. That's why I returned  ``def.js.String`` in all the ``def.js.String`` methods (as you can see in the commit). 

Maybe it was a bad idea, but I would like to have some good reason to convince me. Same, your proposal seems interesting, but it would be good to have some rational reason to go this way (and also, should we generalise that solution to the whole API?). Allowing a method to return a Java or a JS string depending on its parameter types does not seem such a good idea after a little bit of thinking. It might confuse people even more and it is not something you can do for all cases (for instance the ``join()`` with no parameter cannot work this way).

So, IMO, for consistency and simplicity, I think that we should alway return ``def.js.String`` or ``java.lang.String``, but not both. We have to make a choice.

In any case, changing the API now could break some programs... to that's a decision that need to be carefully taken.

About the ``join()`` with no parameters, I can see it in the API. It is [there](https://github.com/cincheo/jsweet/blob/c6a468998ec2e7607bb3f568d83782d495fe4b95/core-lib/es5/src/main/java/def/js/Array.java#L409). So you may have missed it or there must be another logical explanation.

Please be sure that I appreciate all your input. Thanks!

**Comment by travelbasys** [comment]
Good.
Found join() now, too.
Far down after reduce(…).
:-(

Eclipse has a nice „Sort members…“ action.
:-)
It kind of disrupts the diff, of course.

Ok, let’s better be careful about the join() API and better wait.
Maybe someone else gets „confused“ soon.

Thanks and let’s close the thread.
Regards.

**Comment by HubertKauker** [comment]
The question is: 

- would it be acceptable for the _join_ method to have different return types for different argument types, or should there be only one return type, for consistency and simplicity?

Here is an example from the __org.eclipse.jdt.core.JavaCore__ class. There is the _create_ method which has various overloads. For different argument types it does indeed produce different return types.

.  | .
-- | --
static IJavaElement | create(IFile file)
static IJavaElement | create(IFolder folder)
static IJavaProject | create(IProject project)
static IJavaElement | create(IResource resource)
static IJavaElement | create(IResource resource, IJavaProject project)
static IJavaModel | create(IWorkspaceRoot root)
static IJavaElement | create(String handleIdentifier)
static IJavaElement | create(String handleIdentifier, WorkingCopyOwner owner)
