### ISSUE TITLE
Transpiling JSweet using JSweet?

### ISSUE THREAD

**Issue by BrianGenisio** [cincheo/jsweet#380]
Has anyone ever considered transpiling JSweet so that it can run completely in-browser?  It would be really cool to not require a backend transpilation-as-a-service step for code which is authored in-browser (like an IDE, jsFiddle, CodePen, etc).  I'm guessing y'all have thought about it, so was wondering if that is ever something that you might consider, or if there are clear roadblocks to doing it?

**Comment by renaudpawlak** [comment]
Sure, this was already discussed. At that time it was really difficult to do, but now I think we are getting closer. 

However, I suspect it would still require many full days of work and for the outcome I am not sure at all that the performances will be good. That's why so far, we have always preferred using an online transpilation server, which you can find here: https://github.com/cincheo/jsweet-http-server. This server is experimental and would need to be updated for newest versions of JSweet. It is given to the community for the sake of example but it is not meant to be maintained. Anyone can build its own JSweet server relatively easy.

So, back to the main topic, In order to transpile JSweet you first need to transpile a subpart of OpenJDK, the one which contains javac. That's the hardest part. You will require a lot of tuning to avoid transpiling all the API (only the part that it usefull to JSweet). All tuning is explained [there](https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#extending-the-transpiler). Then, you need to support some other minor dependencies such as Apache commons and Google GSON. I expect these to be very easy to support with the new extension API of JSweet v2. Finally, JSweet probably uses JDK APIs that are not yet natively supported such as streams (see issue #379). But that's also easy to support once you have understood how the extension mechanism works.

So, now you see the problem. In theory it would be possible. In practice that would require subsequent development efforts. Unfortunately, I don't have the resources myself :( So, all contributions that would help going in that direction are welcome. That could be a long term goal for the community that can be achieved as a side effect when many more Java APIs will be supported natively.
