### ISSUE TITLE
Local variables used in anonymous classes don't become members

### ISSUE THREAD

**Issue by N3mezis** [cincheo/jsweet#399]
Hi !
Suppose you have the following interface, where `map` is a parameter of the static method that returns an implementation of `ISomething`. Overriding the `getSomething` method, it uses the local variable `map`:
```java
public interface ISomething {
	<O> O getSomething(final String someId);

	static ISomething fromMap(final Map<String, Object> map) {
		return new ISomething() {
			@Override
			public <O> O getSomething(final String someId) {
				return (O) map.get(someId);
			}
		};
	}
}
```

JSweet generates the following code, where the anonymous class's constructor takes a map, but doesn't do anything with it:
```typescript
namespace some.namespace {
    export interface ISomething{
        getSomething<O>(someId: string) : any;
    }

    export namespace ISomething{
        export function fromMap(map : any) : any {
            return new ISomething.ISomething$0(map);
        }
    }

    export namespace ISomething{
        export class ISomething$0 implements some.namespace.ISomething{
            public getSomething<O>(someId: string) : any {
                return <any>this.map.get(someId);
            }

            constructor(private map: any) {
            }
        }
        ISomething$0["__interfaces"] = ["some.namespace.ISomething"];
    }
}
```

`class ISomething$0` should have a private member `map`, that is set in the constructor.

**Comment by TreffnonX** [comment]
As a workaround, have you tried explicitly defining map on your Java-Code?

```Java
public interface ISomething {
	<O> O getSomething(final String someId);

	static ISomething fromMap(final Map<String, Object> map) {
		Map<String, Object> m_map = map;
		return new ISomething() {
			@Override
			public <O> O getSomething(final String someId) {
				return (O) m_map.get(someId);
			}
		};
	}
}
```

While this might not be a fix, it might solve your issue. I did something similar with an iterator-Object and it worked.

**Comment by renaudpawlak** [comment]
This this *not* a bug! :) Please try to run the code and you will see it works (or look at JavaScript generated code rather than TypeScript). Don't believe what your brain tells you and let TypeScript operate its magic ;)

TypeScript has a special syntax that allows you to declare a field and initialize it just by declaring a constructor parameter. You just need to add a visibility modifier to a constructor parameter. Here:

```TypeScript
constructor(private map: any) {
}
```

Is exactly the same as:

```TypeScript
private map: any;
constructor(map: any) {
    this.map = map;
}
```

That's because of the ``private`` visibility modifier. Since it is a common idiom, it is pretty convenient, also quite confusing when not aware of this very special construct (as you have experienced).

More info on this random [blog](https://www.stevefenton.co.uk/2013/04/stop-manually-assigning-typescript-constructor-parameters/), and this [one](https://kendaleiv.com/typescript-constructor-assignment-public-and-private-keywords/) for instance.
