### ISSUE TITLE
Union of string types?

### ISSUE THREAD

**Issue by nedtwigg** [cincheo/jsweet#412]
It there a way to create a union of string types?  Here's a simple testcase you can see in [the live sandbox](http://www.jsweet.org/jsweet-live-sandbox/).

```java
@jsweet.lang.Interface
public class DocumentFact {
	@jsweet.lang.StringType
	public interface movie {}
	@jsweet.lang.StringType
	public interface book {}

	public String title;
	public jsweet.util.union.Union<movie, book> kind;
	public movie movieKind;
	public book bookKind;
}
```

```typescript
interface DocumentFact {
    title : string;
    kind : ((DocumentFact.movie)|(DocumentFact.book));
    movieKind : "movie";
    bookKind : "book";
}

namespace DocumentFact {
    export interface movie {    }
    export interface book {    }
}
```

I'd expect `kind: "movie" | "book"`.  Just as good would be if I could do something like `@jsweet.lang.FieldType("'movie' | 'book'")`.

**Comment by renaudpawlak** [comment]
Hi. Nope, there is no way to have unions of string types in JSweet so far. Unions work, but for regular types only. It is quite a difficult issue, because the idea of JSweet is to keep the Java type system as is.  Unions and string types are part of the types we can emulate but really it does not look good (and if you add string types AND unions, it would be even worse). I would loosen the typing most of the time to avoid bad looking code :(

That said, there is an extension I wrote for supporting string type unions with enums. It is kind of a hack but it works quite well. It consists of describing the union type with an enum:

```java
@StringType public enum Kind {
  movie, book;
}
```

Then you can write:

```java
Kind kind = Kind.book;
```

And it will generate the following TS code:

```TypeScript
kind : string = "book";
```

I guess it would not be too hard to tune the extension to have it generate:

```TypeScript
kind : "book" | "movie" = "book";
```

The extension is not standard and should be installed as explained in the documentation.
Extension code: [here](https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#example-4-an-adapter-to-map-enums-to-strings).
How to install extensions: read [here](https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#programmatic-tuning-with-adapters).

I guess the extension should have to be adapted to fit your use case... if it does, maybe it could be a good idea to add this extension to JSweet as a standard feature...

**Comment by nedtwigg** [comment]
Does JSweet have an "escape hatch", such as `@jsweet.lang.GenerateTypeAs("\"book\" | \"movie\"")`?  Your `StringType public enum Kind` is an elegant solution for this particular problem, but it would be cool to have more general mechanism for cases where TypeScript and Java can't be made to agree precisely.

**Comment by nedtwigg** [comment]
I see that there is `jsweet.lang.Replace`, but it only works for methods, not fields.  I'll close this out as dupe of #614.
