### ISSUE TITLE
Tranpilation with typeScript Defintion files replacing the java classes

### ISSUE THREAD

**Issue by courteous** [cincheo/jsweet#417]
I have a  java project. Jsweet is able to transpile everything well except one simple class i.e. the java  ByteBuffer class. Instead of the Java ByteBuffer i am using the ByteBuffer.js  together with its typescript definitions files. For that purpose in the root of my java project i have create a folder with a name "def" as described 
[here](https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#bridging-to-external-javascript-elements)

and placed the typescript definition file (ByteBuffer.d.ts) of the bytebuffer.js into that folder 

Now my target is that when i run:

mvn jsweet:jsweet`

the jsweet  will scan for he definitions in the "def" folder i.e. for the file with a name ByteBuffer.d.ts and later it will automatically import the ByteBuffer in all places where it should be required, thus replacing the Java ByteBuffer declaration.

instead of that the jsweet writes the type i.e. something like:

`value: ByteBuffer;`

which is still good, but it does not automatically create an import statement something like

`import * as ByteBuffer from '../base/ByteBuffer';`

what i am doing wrong here? I have tried placing that def folder already in multiple locations thinking that this might be the wrong location but still no luck.
The documantation states that the folder name should be "def.libname" is there any working example where i can take a look how this looks like?

any feedback is really appreciated.

**Comment by renaudpawlak** [comment]
Hello. Sorry for late answer.

The case of replacing a core java class (such as ByteBuffer) by a js implementation is a special case. 

Here some hints:
- You don't need to write a def, because the class is already accessible by the Java compiler. On the other hand you may need to define type mapping in order to map the Java type to the actual Java (for example ``java.nio.ByteBuffer`` => ``base.ByteBuffer``.
- If imports are needed, you will need to write an adapter that will inject the right imports, however, I don't believe you need it if you map the  ``java.nio.ByteBuffer`` to another custom type (imports should be generated automatically).

You should find some useful examples in the specs, for instance the BigDecimal extension could be a good start for you: https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#example-3-an-adapter-to-support-java-bigdecimal
