### ISSUE TITLE
Is LinkedList/Deque supported by JSweet?

### ISSUE THREAD

**Issue by holoduck** [cincheo/jsweet#504]
Transpiling a module which uses the Deque API throws errors.

As an example, I modified the [QuickStart app](https://github.com/cincheo/jsweet-quickstart.git) from the [Getting Started guide](http://www.jsweet.org/getting-started/) to use a LinkedList instead of the List's methods  as follows:

```
import java.util.LinkedList;
import java.util.List;

import def.js.Array; 

public class QuickStart {

	public static void main(String[] args) {
		// you can use regular Java API
		LinkedList<String> l = new LinkedList<>();
		l.add("Hello");
		l.add("world");
		l.peekLast();
		//..
	}
}
```

Transpilation fails with the following error:
`ERROR output:55 - property 'peekLast' does not exist on type 'string[]' at /.../src/main/java/quickstart/QuickStart.java(21)`

**Comment by lgrignon** [comment]
Hello,
With JSweet 2.2.0-SNAPSHOT, most of the Collections API is supported but it seems that peekLast isn't.

As a workaround, you could use isEmpty ? null : get(size - 1), but this is not fully satisfying :)

Would you want to make a PR, this bug seems pretty easy to fix, around here I'd say:
https://github.com/cincheo/jsweet/blob/master/transpiler/src/main/java/org/jsweet/transpiler/extension/RemoveJavaDependenciesAdapter.java#L1144

**Comment by lgrignon** [comment]
Hey @octachrome, any news on this?
It should be possible around here 
https://github.com/cincheo/jsweet/blob/develop/transpiler/src/main/java/org/jsweet/transpiler/extension/RemoveJavaDependenciesAdapter.java#L1105
