### ISSUE TITLE
Repository Temporarily Unavailable

### ISSUE THREAD

**Issue by Cavva79** [cincheo/jsweet#515]
Hi @renaudpawlak 

it seems http://repository.jsweet.org/artifactory/ is down.
```
Service Temporarily Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.2.22 (Debian) Server at repository.jsweet.org Port 80
```
Thank you

**Comment by npfoss** [comment]
Has anyone found a way to run this code at all without jsweet.org? Even the build process (mvn package) seems to rely on jsweet.org...

**Comment by renaudpawlak** [comment]
We are working on it. Our back-end server crashed (all CI, sandbox, and Maven repo). Grub failure apparently. We are trying to make it boot again so that we don't have to re-install everything and have the service back ASAP (hopefully the repair will work). 
Clearly, in any case this should raise a discussion about switching to another solution (and even organization)...
Really really sorry for the inconvenience.

**Comment by DanieleCostamagna** [comment]
Repository is working again: fast and reliable. Thanks, @renaudpawlak.

**Comment by renaudpawlak** [comment]
Current status: the OS is dead (for some enigmatic reason) and we cannot fix it. So, @lgrignon is currently taking care of backuping the data and will then reinstall a new OS. Then he will reinstall our repo first so that the service goes back to normal ASAP. Then, we will move/duplicate the repo somewhere else to avoid this situation in the future.  Thank you all for your patience.

**Comment by tevch** [comment]
Is it possible you guys archive the jsweet specific dependencies and have it accessible until server is fixed? Just my luck that i need to redeploy my app today :)

**Comment by lgrignon** [comment]
Hello, 
Could you please try again? It should be back online.

**Comment by joshuagruenstein** [comment]
It may also be a good idea to provide instructions somewhere on how to build a jsweet project without using an external jsweet artifactory, just using a cloned version of jsweet github repos.  This was difficult for me to figure out during the outage.

**Comment by tevch** [comment]
Works. Thank you very much

**Comment by Cavva79** [comment]
Thank you @lgrignon and @renaudpawlak.

Have you thought about the official maven central repository?
Maybe your repo could be used for snapshots and sonatype oss for releases?

**Comment by Cavva79** [comment]
Thank you @renaudpawlak  and @lgrignon :)

This is the [official guide](https://central.sonatype.org/pages/ossrh-guide.html).
I did it for one maven plugin I made some years ago, and I may help you. :)

**Comment by lgrignon** [comment]
Thanks for the intel! :)

We just discussed it this morning. We will keep JSweet's dedicated maven repository, as advised here: https://maven.apache.org/repository-management.html

But we will sync it with a central repository, to avoid SPOF. This should be easily doable since we use Artifactory.

I keep your guide, it may be useful!

We will keep you informed. 
Bye.

**Comment by lgrignon** [comment]
Hello again,
Finally we synced with JFrog's Bintray because it's well integrated with Artifactory (of course :)).

I only deployed former release and we intent to perform a quick release soon of 2.2.0 since it is pretty stable.

Bye.

**Comment by Cavva79** [comment]
Hi @lgrignon,

thanks you for the best support you and @renaudpawlak are giving to us.
I'd like to ask you something about bintray, is there a function described [here](https://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/)?
If there is, why not to complete the maven central integration?

thank you again
