### ISSUE TITLE
Publish to JSweet to Maven Central

### ISSUE THREAD

**Issue by bdemers** [cincheo/jsweet#565]
Please ;) 
https://central.sonatype.org/pages/ossrh-guide.html

**Comment by lgrignon** [comment]
Hello @bdemers 
JSweet is already published to bintray (I just updated the published versions so you can enjoy the last 2.3.5).
It should be enough, why do you want JSweet to be published rather on Sonatype's central?

**Comment by lgrignon** [comment]
I noticed the Bintray's feature to sync artifacts to central. It seems to work seemlessly now, I will give it a try for JSweet artifacts.

**Comment by lgrignon** [comment]
There are some requirements to match: https://central.sonatype.org/pages/requirements.html
This implies modifications in project and is not high priority IMHO.

Could you please close issue to confirm that Bintray's jcenter is working for you?
https://bintray.com/bintray/jcenter?filterByPkgName=jsweet-*

**Comment by bdemers** [comment]
In general, I avoid using 3rd party artifact repositories. for a few reasons,

1.) ease of use, It's the default repo for Maven installations (Apache Maven uses the URL https://repo.maven.apache.org/maven2/ which has _some_ oversite by the Maven project)
2.) Quality, I know If I use artifacts from central there are minimum requirements met, signed artifacts, etc
3.) If I wanted to put a library in Central, but I was dependent on a library out of central it provides a poor user experience (IIRC this was blocked at one point).

Which requirements are you missing? Maybe I can help?

**Comment by lgrignon** [comment]
Got you. It is basically about making pom ready for central if it does not meet the requirements yet, and also signing those artifacts.

**Comment by lgrignon** [comment]
Just as a side info, the error I get from central when I try to publish from bintray is 

![image](https://user-images.githubusercontent.com/6956079/78585423-24429100-783a-11ea-837d-8eaf118940b2.png)

**Comment by lgrignon** [comment]
I finally succeeded in signing those jars.

![image](https://user-images.githubusercontent.com/6956079/78591173-4d1b5400-7843-11ea-8c5a-255926fc4dde.png)

**Comment by lgrignon** [comment]
Ok, I got it

![image](https://user-images.githubusercontent.com/6956079/78592564-91a7ef00-7845-11ea-86f4-425439aea072.png)

For now, it's just jsweet-transpiler artifact. I will publish on central the other main artifacts soon:
* jsweet-core
* jsweet-maven-plugin
* jsweet-gradle

However, it is not realistic to have all JSweet candies published to maven central because there are a lot of them and publishing to maven central is a manual operation. JSweet without candies is not really JSweet, but main artifacts will at least be available on central, and users requiring candies can use the 3rd party repository.

**Comment by lgrignon** [comment]
Here you go:
https://repo.maven.apache.org/maven2/org/jsweet/
