### ISSUE TITLE
TypeScript to JavaScript transpilation using tsc (not tsserver) fails when too many files

### ISSUE THREAD

**Issue by frankcapodanno** [cincheo/jsweet#605]
Hi,

I have a problem when I try to parse a big project from ts to js with Jsweet. It seems that there is a limit in the command when many ts were generated. (Plugin with transpiler version 2.3.8) :

`TypeScript2JavaScriptWithTscTranspiler:94 - command line is too long.`

Maybe could be an idea when a lot of ts files was generated from ts to js would be divided in different calls to the command (tsc transpieler).

OS: Windows 10
Java : 8 (251)
Transpieler Version : 2.3.8

Detail of the call that generate an error on a big project:

user\.jsweet-node_modules\tsc.cmd, --target, ES5, --moduleResolution, classic, --experimentalDecorators, --emitDecoratorMetadata, --rootDir, C:\projekt\example\jsweetparse\ts, --outDir, C:\projekt\example\jsweetparse\js, .tsc-rootfile.ts, [HERE TOO MANY FILES]

**Comment by renaudpawlak** [comment]
Looks like a common issue with [ProcessBuilder](https://github.com/cincheo/jsweet/blob/develop/transpiler/src/main/java/org/jsweet/transpiler/util/ProcessUtil.java#L267).
The limit is around [2000 characters](https://stackoverflow.com/questions/41889981/limit-on-commands-for-a-processbuilder). 

However, I am surprised because I know users who compile fairly big (even very big) projects and that don't run into such a limitation. I will ask how many files they compile.

In the meantime, can you consider splitting your project into modules? What you can do, is to adjust the [input option](https://github.com/cincheo/jsweet/blob/7d42942707fd143e6b16a5d0600df631edc1f268/transpiler/src/main/java/org/jsweet/JSweetCommandLineLauncher.java#L85) *and* the exclusion patterns to partially transpile your project (exclusion patterns will filter out some Java files from the transpilation so they will not be passed to the TypeScript-to-JavaScript transpilation.

**Comment by frankcapodanno** [comment]
I think that's good., and thank you for the suggestion. I try something with my project but is not urgent and I try something with exclusions and inclusion patterns. But if you change input option that will be affected and also supported to the Maven Plugin ? Sorry for this newbie question.  Thank you for your answer.

**Comment by lgrignon** [comment]
I think you can also avoid this problem by using the tsserver option (available with maven plugin as well) which AFAIK does not suffer this limitation.

The other question about includes/excludes has been answered here:
https://github.com/lgrignon/jsweet-maven-plugin/issues/52#issuecomment-684509538

I keep this issue open and change title

**Comment by lgrignon** [comment]
@renaudpawlak I guess tsserver could be the default mode now? What do you think.

A workaround could be to minimize the file list by using relative paths from a root di if not done yet.

**Comment by lgrignon** [comment]
Paths are already as short as possible. 
Let's tsserver be the default mode for JSweet 3

**Comment by lgrignon** [comment]
@renaudpawlak request for confirmation :)
