### ISSUE TITLE
bundle option enhancements

### ISSUE THREAD

**Issue by lgrignon** [cincheo/jsweet#61]
While using the bundle options, there are some annoying points which, IMO, could be easily fixed: 

- bundle is not enabled if bundlesDIrectory is specified without the bundle option, it could be more intuitive to enable bundles if bundlesDirectory is set
- bundle requires the module option to be activated. JSweet throws a very shy error if this option isn't enabled but completely screw the bundle's generation. It would be better to default to module=commonjs if bundle=true
- bundle requires to order properly files inclusion that one class defines a main. I think JSweet should raise a fatal error (blocking compilation) if this requirement is not met.
- if bundle option is activated, JSweet tries to download / install all candies as NPM packages and then bundle them with project's code. Pretty heavy huh? What do you think about the following option:
&lt;bundleExcludedCandies&gt;	&#10;
&nbsp;&nbsp;&lt;exclude&gt;angular&#42;&lt;&frasl;exclude&gt;	&#10;
&nbsp;&nbsp;&lt;exclude&gt;&#42;&lt;&frasl;exclude&gt;	&#10;
&lt;&frasl;bundleExcludedCandies&gt;

or maybe something clearer like:

&lt;bundleIncludeCandies&gt;false&lt;/bundleIncludeCandies&gt;

Thanks.

**Comment by renaudpawlak** [comment]
Note: bundle is a convenience option for programmers. It uses browserify under the hood to bundle the sources in a default but simple way. Since there are existing bundlers out there, this bundle support should remain very basic and simple, so that it is clear that JSweet should not substitute to these tools. In short, yes, using the bundle option should be very intuitive and simple, but no, I don't think that extra configuration such as excluding candies should be supported by JSweet. When wanting specific or performant bundling, users should start doing their own bundlers.

**Comment by renaudpawlak** [comment]
These points are solved or made irrelevant by the new bundle system of 1.1.0.
