### ISSUE TITLE
Error while building with Java 8

### ISSUE THREAD

**Issue by norzak** [cincheo/jsweet#635]
Caused by: java.lang.UnsupportedClassVersionError: org/jsweet/JSweetMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.

It looks like some files are compiled with Java 11.

**Comment by lgrignon** [comment]
Which version of the jsweet maven plugin please?

**Comment by norzak** [comment]
I have just followed what is written in http://www.jsweet.org/getting-started/. It should be the latest version I presume.

**Comment by norzak** [comment]
[ERROR] Failed to execute goal org.jsweet.v3:jsweet-maven-plugin:3.0.0-SNAPSHOT:

**Comment by lgrignon** [comment]
JSweet 3 requires Java 11 indeed. Latest version is 3.0.0-RC7
JSweet 2.x sticks with Java 8. Latest version is: 2.3.10
Note: I would recommend using JSweet 3 with Java 11 if you can because it will be the main version in the future. 

Please try again and close this issue if this fixes your problem.

(JSweet versions: https://github.com/cincheo/jsweet/tags)

**Comment by norzak** [comment]
Okay
