### ISSUE TITLE
property 'isAssignableFrom' does not exist on type '"java.util.Collection"'

### ISSUE THREAD

**Issue by Oleksandr-Silin** [cincheo/jsweet#650]
I'm trying to transpile a set of java classes as library shared between backend and frontend.

I'm using: JSweetVersion = "3.0.0"

I have method with next condition:
```
public String format(final Object value) {
   if (Collection.class.isAssignableFrom(value.getClass())){
....
```
I receive next error:
```
property 'isAssignableFrom' does not exist on type '"java.util.Collection"' at 
```

PS: Other small issue, transpiled budle.ts can't be imported as module, until I add to all produced namespaces export.
my configuration:
```
jsweet {
	verbose = true
	encoding = 'UTF-8'
	sourceMap = true
	outDir = project.file('dist/js')
	tsOut =  project.file('dist/ts')
	targetVersion = EcmaScriptComplianceLevel.ES6
	includes = ['**/com/**/*.java']
	bundle = true
}
```
PS2:
Could you point me to information how to extend transpiler with new types. I want to add/have support for java.util.Locale, java.text package.

Thank you for your help!

**Comment by lgrignon** [comment]
Hello, thanks for reporting
FYI you can now use JSweet 3.1.0-SNAPSHOT to enjoy latest improvements.

If `bundle = true`is enabled, then it cannot be module mode. If you set bundle to false, JSweet will generate module files, and you can choose module mode with several options (please see README for more details)

The transpiler is highly extensible, as you can see: https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#extending-the-transpiler
but given your needs, you may want to consider using J4TS : 
https://github.com/j4ts/j4ts/
https://github.com/lgrignon/j4ts-example

I keep this issue open because there might be a bug in isAssignableFrom
