### ISSUE TITLE
Candy support for Angular 2 - currently it's empty!

### ISSUE THREAD

**Issue by grantsheer** [cincheo/jsweet#78]
Hi There

Are you going to have support for annotations in TypeScript of the `@Component` variety in Angular 2 [here](https://angular.io/docs/ts/latest/quickstart.html)? If not what do you suggest we do to support its constructs for building Angular 2 MVC apps; and if so, when do you think that it will be available?

Also, I notice that Angular 2 is in your candy repo, but when I declare it as a dependency in my POM, the API packages are not there; and the 2.0.0-SNAPSHOT version is newer than 2.0.1/2-SNAPSHOT(!):
![angular2packages](https://cloud.githubusercontent.com/assets/17410893/13251639/27c69e04-da3a-11e5-9f05-2566dc889762.PNG)

I notice that it is not in the DefinitelyTyped repo, but moved a little while ago to the [npm repo here]
(https://www.npmjs.com/package/angular2).

Are you planning on importing it. If not, how would you suggest we use it (perhaps in the meantime), until it is correctly in your candy repo?

Thanks so much for an amazing project!

**Comment by renaudpawlak** [comment]
Hi! For Angular 2, we need first to have support for annotations (they are called decorators in TypeScript). This is planned issue #43. I don't really understand why it is published as an empty candy, but it is clearly not usable before we have annotations anyway.

For candy versions, we need to clean the repo because versions x.y.1 and x.y.2 are obsolete. You should use the exact same version as they appear in the TSD repo, i.e. x.y.0 most of the time. (0.0.0 means latest).

Thanks for your nice words about JSweet :)

**Comment by grantsheer** [comment]
Top stuff. Much appreciate your speedy reply.

Take care.

**Comment by kito99** [comment]
Shouldn't we lave the this open? The candy is still empty...
