### ISSUE TITLE
missing jsweet.dom.HTMLOptionsCollection 

### ISSUE THREAD

**Issue by ssatguru** [cincheo/jsweet#83]
HTMLSelectElement.options should return HTMLOptionsCollection 
Currently it just returns HTMLSelectElement

**Comment by renaudpawlak** [comment]
You are right. It is a bug in the version of the ``lib.dom.d.ts`` we are currently using. I have checked, it is fixed in the latest version, so we will just update it (actually the new version defines it as ``options: HTMLCollection``. I'll tell you when it is done. Meanwhile you can use a brute-force cast.

**Comment by renaudpawlak** [comment]
I have just updated the core libs so ``options`` should be of the right type now. Some small modifications might be required in your programs, especially where unions are at play.

**Comment by ssatguru** [comment]
nice. thanks
